      SUBROUTINE DRAWBY(KSYM)
C***********************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
      PARAMETER (LI=361,LJ=131,IPMAX=500,JPMAX=200)
      COMMON/CB03/ DT,X(LJ,LI),Y(LJ,LI),XXC(LI),XXS(LI),YYC(LJ),YYS(LJ)           
      COMMON/BODY/NBODY,IBDM(10),JBDM(10),IBDP(10),JBDP(10),TBD(10)
      COMMON/APIXL/ IPAGE,NCOLOR,NBACK,NAA(IPMAX,JPMAX)
      COMMON/FRAME/ IPIXL,JPIXL,XMIN,YMIN,XMAX,YMAX,XPIXL,YPIXL
      NCOLOR=255
      DO 200 N=1,NBODY
      IBODYM=IBDM(N)
      IBODYP=IBDP(N)
      JBODYM=JBDM(N)
      JBODYP=JBDP(N)
      DY=(YMAX-YMIN)/FLOAT(JPIXL)
      XA=X(JBODYM,IBODYM)
      IF(XA.LT.XMIN) XA=XMIN
      XB=X(JBODYP,IBODYP)
      IF(XB.GT.XMAX) XB=XMAX
      IF(XB.LT.XMIN) XB=XMIN
      YA=Y(JBODYM,IBODYM)
      IF(YA.LT.YMIN) YA=YMIN
  100 CONTINUE
      CALL LINE(XA,YA,XB,YA)
      IF(KSYM.EQ.1) CALL LINE(XA,-YA,XB,-YA)
      YA=YA+DY
      IF(YA.LE.Y(JBODYP,IBODYP).AND.YA.LE.YMAX) GO TO 100
  200 CONTINUE
      RETURN
      END