      SUBROUTINE PERTRB(IANOIS,IBNOIS,JANOIS,JBNOIS)
C***********************************************************************
      IMPLICIT REAL *8 (A-H,O-Z)                                        
      PARAMETER(LI=711,LJ=131,LE=LI*LJ,LSP=52)        
      COMMON/CB01/ ISYM,IFLOW,ISWRL,ITHRM,ICHEM,IGRAV,ITR,ISKIP(LE)                  
      COMMON/CB02/ RREF,VREF,TREF,PREF,WM(LSP)
      COMMON/CB03/ DT,X(LJ,LI),Y(LJ,LI),XXC(LI),XXS(LI),YYC(LJ),YYS(LJ)           
      COMMON/CB04/ RHO(LJ,LI),FSP(LJ,LI,LSP),U(LJ,LI),V(LJ,LI),
     1  W(LJ,LI),P(LJ,LI),HT(LJ,LI),TK(LJ,LI),AK(LJ,LI),EPS(LJ,LI)
      COMMON/CB06/ ALSTR,VSTR,RSTR,PSTR,TSTR,TMSTR,AMSTR,ACSTR,DSTR,  
     1  HSTR,CPSTR,AKSTR,EPSTR,WMSTR,GASC,BETA1,BETA2,BETA3,BETA4,REI         
      COMMON/NOISE/ INOISE,IVXTYP,FNOISE,ANOISE(200),VXTYP(5),TTIME
      PI2=2.0*3.141592654
      ICENT=(IANOIS+IBNOIS)/2
      JCENT=(JANOIS+JBNOIS)/2
      FT=TTIME*FNOISE
      FTIME=PI2*(FT-DFLOAT(INT(FT)))
      RADO=DSQRT((X(JBNOIS,IBNOIS)-X(JCENT,ICENT))**2
     1    +(Y(JBNOIS,IBNOIS)-Y(JCENT,ICENT))**2)
      DO 20 I=IANOIS,IBNOIS
      DO 22 J=JANOIS,JBNOIS
            
       IF(I.EQ.ICENT.AND.J.EQ.JCENT) GO TO 22
       YA=Y(J,I)-Y(JCENT,ICENT)
       XA=X(J,I)-X(JCENT,ICENT)
C      RAD=DSQRT(XA*XA+YA*YA)
      RAD=RADO
       R1=DCOS(FTIME*RADO/RAD)/RAD
       R2=DSIN(FTIME*RADO/RAD)/RAD
       U(J,I)=U(J,I)-ANOISE(1)*(YA*R1+XA*R2)
       V(J,I)=V(J,I)-ANOISE(1)*(XA*R1-YA*R2)
   22 CONTINUE
   20 CONTINUE
      RETURN
      END