      
      INCLUDE 'lib\ckrates.f'
      INCLUDE 'lib\solvesp.f'
      INCLUDE 'lib\solveh.f'

      SUBROUTINE SPGSOLV(ISOR1,RELXSP,TOLRSP,RESDC,
     1  ISOR2,RELXH,TOLRH,RESDH,SIGH,SIGSP)
C***********************************************************************
      IMPLICIT REAL *8 (A-H,O-Z)
      PARAMETER(LI=711,LJ=131,LE=LI*LJ,LJ2=LJ*2,LSP=52,LRX=544)
      COMMON/CB01/ ISYM,IFLOW,ISWRL,ITHRM,ICHEM,IGRAV,ITR,ISKIP(LJ,LI)                  
      COMMON/CB02/ RREF,VREF,TREF,PREF,WM(LSP)
      COMMON/CB03/ DT,X(LJ,LI),Y(LJ,LI),XXC(LI),XXS(LI),YYC(LJ),YYS(LJ)           
      COMMON/CB04/ RHO(LJ,LI),FA0(LJ,LI),FA1(LJ,LI),FA2(LJ,LI),
     *  FA3(LJ,LI),FA4(LJ,LI),FA5(LJ,LI),FA6(LJ,LI),FA7(LJ,LI),
     *  FA8(LJ,LI),FA9(LJ,LI),FAA(LJ,LI),FAB(LJ,LI),FAC(LJ,LI),
     *  FAD(LJ,LI),FAE(LJ,LI),FAF(LJ,LI),FAG(LJ,LI),FAH(LJ,LI),
     *  FAI(LJ,LI),FAJ(LJ,LI),FB0(LJ,LI),FB1(LJ,LI),FB2(LJ,LI),
     *  FB3(LJ,LI),FB4(LJ,LI),FB5(LJ,LI),FB6(LJ,LI),FB7(LJ,LI),
     *  FB8(LJ,LI),FB9(LJ,LI),FBA(LJ,LI),FBB(LJ,LI),FBC(LJ,LI),
     *  FBD(LJ,LI),FBE(LJ,LI),FBF(LJ,LI),FBG(LJ,LI),FBH(LJ,LI),
     *  FBI(LJ,LI),FBJ(LJ,LI),FC0(LJ,LI),FC1(LJ,LI),FC2(LJ,LI),
     *  FC3(LJ,LI),FC4(LJ,LI),FC5(LJ,LI),FC6(LJ,LI),FC7(LJ,LI),
     *  FC8(LJ,LI),FC9(LJ,LI),FCA(LJ,LI),FCB(LJ,LI),
     *  U(LJ,LI),V(LJ,LI),W(LJ,LI),P(LJ,LI),HT(LJ,LI),TK(LJ,LI),
     *  AK(LJ,LI),EPS(LJ,LI)
      COMMON/CB06/ ALSTR,VSTR,RSTR,PSTR,TSTR,TMSTR,AMSTR,ACSTR,DSTR,  
     1  HSTR,CPSTR,AKSTR,EPSTR,WMSTR,GASC,BETA1,BETA2,BETA3,BETA4,REI         
      COMMON/CB07/ VMU(LJ,LI),VTC(LJ,LI),VDF(LJ,LI,LSP),TMU(LJ,LI)
      COMMON/CB08/ TPOL1,TPOL2,POLSP(14,LSP),CISP(12,LSP)
      COMMON/CB09/ IBOT(LI),ITOP(LI),JLFT(LJ),JRGT(LJ),
     1       FBOT(8+LSP,LI),FTOP(8+LSP,LI),FLFT(8+LSP,LJ),FRGT(8+LSP,LJ)
      COMMON/CB10/ FBXP(4,LJ),FBXM(4,LJ),FBYP(4,LI),FBYM(4,LI)
      COMMON/REAC/ LREV,NRLIND,ITBEF(LRX),ALF(LRX),AKF(LRX),EXAF(LRX),
     1             ALLOW(LRX),AKLOW(LRX),EALOW(LRX),TROE(LRX,4)
      COMMON/HFORM/ HFO(LSP)
      COMMON/KEPS/ AKREF,EPREF,C1KE,C2KE,CMKE,CMKEQ,EE,AVON,PCON
      COMMON/SOOT/ RSOOT,STMF(LJ,LI),STND(LJ,LI),STDF(LJ,LI)
      COMMON/DUMMY/
     *  EA0(LJ,LI),WA0(LJ,LI),PA0(LJ,LI),QA0(LJ,LI),EA1(LJ,LI),
     *  WA1(LJ,LI),PA1(LJ,LI),QA1(LJ,LI),EA2(LJ,LI),WA2(LJ,LI),
     *  PA2(LJ,LI),QA2(LJ,LI),EA3(LJ,LI),WA3(LJ,LI),PA3(LJ,LI),
     *  QA3(LJ,LI),EA4(LJ,LI),WA4(LJ,LI),PA4(LJ,LI),QA4(LJ,LI),
     *  EA5(LJ,LI),WA5(LJ,LI),PA5(LJ,LI),QA5(LJ,LI),EA6(LJ,LI),
     *  WA6(LJ,LI),PA6(LJ,LI),QA6(LJ,LI),EA7(LJ,LI),WA7(LJ,LI),
     *  PA7(LJ,LI),QA7(LJ,LI),EA8(LJ,LI),WA8(LJ,LI),PA8(LJ,LI),
     *  QA8(LJ,LI),EA9(LJ,LI),WA9(LJ,LI),PA9(LJ,LI),QA9(LJ,LI),
     *  EAA(LJ,LI),WAA(LJ,LI),PAA(LJ,LI),QAA(LJ,LI),EAB(LJ,LI),
     *  WAB(LJ,LI),PAB(LJ,LI),QAB(LJ,LI),EAC(LJ,LI),WAC(LJ,LI),
     *  PAC(LJ,LI),QAC(LJ,LI),EAD(LJ,LI),WAD(LJ,LI),PAD(LJ,LI)
      COMMON/DUM0/
     *  QAD(LJ,LI),EAE(LJ,LI),WAE(LJ,LI),PAE(LJ,LI),QAE(LJ,LI),
     *  EAF(LJ,LI),WAF(LJ,LI),PAF(LJ,LI),QAF(LJ,LI),EAG(LJ,LI),
     *  WAG(LJ,LI),PAG(LJ,LI),QAG(LJ,LI),EAH(LJ,LI),WAH(LJ,LI),
     *  PAH(LJ,LI),QAH(LJ,LI),EAI(LJ,LI),WAI(LJ,LI),PAI(LJ,LI),
     *  QAI(LJ,LI),EAJ(LJ,LI),WAJ(LJ,LI),PAJ(LJ,LI),QAJ(LJ,LI),
     *  EB0(LJ,LI),WB0(LJ,LI),PB0(LJ,LI),QB0(LJ,LI),EB1(LJ,LI),
     *  WB1(LJ,LI),PB1(LJ,LI),QB1(LJ,LI),EB2(LJ,LI),WB2(LJ,LI),
     *  PB2(LJ,LI),QB2(LJ,LI),EB3(LJ,LI),WB3(LJ,LI),PB3(LJ,LI),
     *  QB3(LJ,LI),EB4(LJ,LI),WB4(LJ,LI),PB4(LJ,LI),QB4(LJ,LI),
     *  EB5(LJ,LI),WB5(LJ,LI),PB5(LJ,LI),QB5(LJ,LI),EB6(LJ,LI),
     *  WB6(LJ,LI),PB6(LJ,LI),QB6(LJ,LI),EB7(LJ,LI),WB7(LJ,LI),
     *  PB7(LJ,LI),QB7(LJ,LI),EB8(LJ,LI),WB8(LJ,LI),PB8(LJ,LI),
     *  QB8(LJ,LI),EB9(LJ,LI),WB9(LJ,LI),PB9(LJ,LI),QB9(LJ,LI),
     *  EBA(LJ,LI),WBA(LJ,LI),PBA(LJ,LI),QBA(LJ,LI),EBB(LJ,LI),
     *  WBB(LJ,LI),PBB(LJ,LI),QBB(LJ,LI),EBC(LJ,LI),WBC(LJ,LI),
     *  PBC(LJ,LI),QBC(LJ,LI),EBD(LJ,LI),WBD(LJ,LI),PBD(LJ,LI),
     *  QBD(LJ,LI),EBE(LJ,LI),WBE(LJ,LI),PBE(LJ,LI),QBE(LJ,LI),
     *  EBF(LJ,LI),WBF(LJ,LI),PBF(LJ,LI),QBF(LJ,LI),EBG(LJ,LI),
     *  WBG(LJ,LI),PBG(LJ,LI),QBG(LJ,LI),EBH(LJ,LI),WBH(LJ,LI),
     *  PBH(LJ,LI),QBH(LJ,LI),EBI(LJ,LI),WBI(LJ,LI),PBI(LJ,LI),
     *  QBI(LJ,LI),EBJ(LJ,LI),WBJ(LJ,LI),PBJ(LJ,LI),QBJ(LJ,LI),
     *  EC0(LJ,LI),WC0(LJ,LI),PC0(LJ,LI),QC0(LJ,LI),EC1(LJ,LI),
     *  WC1(LJ,LI),PC1(LJ,LI),QC1(LJ,LI),EC2(LJ,LI),WC2(LJ,LI),
     *  PC2(LJ,LI),QC2(LJ,LI),EC3(LJ,LI),WC3(LJ,LI),PC3(LJ,LI),
     *  QC3(LJ,LI),EC4(LJ,LI),WC4(LJ,LI),PC4(LJ,LI),QC4(LJ,LI),
     *  EC5(LJ,LI),WC5(LJ,LI),PC5(LJ,LI),QC5(LJ,LI),EC6(LJ,LI),
     *  WC6(LJ,LI),PC6(LJ,LI),QC6(LJ,LI),EC7(LJ,LI),WC7(LJ,LI),
     *  PC7(LJ,LI),QC7(LJ,LI),EC8(LJ,LI),WC8(LJ,LI),PC8(LJ,LI),
     *  QC8(LJ,LI),EC9(LJ,LI),WC9(LJ,LI),PC9(LJ,LI),QC9(LJ,LI),
     *  ECA(LJ,LI),WCA(LJ,LI),PCA(LJ,LI),QCA(LJ,LI)
      COMMON/DUMX/ ZE(LJ,LI),ZW(LJ,LI),ZN(LJ,LI),ZS(LJ,LI)
      COMMON/DUMY/            SA0(LJ,LI),SA1(LJ,LI),SA2(LJ,LI),
     *  SA3(LJ,LI),SA4(LJ,LI),SA5(LJ,LI),SA6(LJ,LI),SA7(LJ,LI),
     *  SA8(LJ,LI),SA9(LJ,LI),SAA(LJ,LI),SAB(LJ,LI),SAC(LJ,LI),
     *  SAD(LJ,LI),SAE(LJ,LI),SAF(LJ,LI),SAG(LJ,LI),SAH(LJ,LI),
     *  SAI(LJ,LI),SAJ(LJ,LI),SB0(LJ,LI),SB1(LJ,LI),SB2(LJ,LI),
     *  SB3(LJ,LI),SB4(LJ,LI),SB5(LJ,LI),SB6(LJ,LI),SB7(LJ,LI),
     *  SB8(LJ,LI),SB9(LJ,LI),SBA(LJ,LI),SBB(LJ,LI),SBC(LJ,LI),
     *  SBD(LJ,LI),SBE(LJ,LI),SBF(LJ,LI),SBG(LJ,LI),SBH(LJ,LI),
     *  SBI(LJ,LI),SBJ(LJ,LI),SC0(LJ,LI),SC1(LJ,LI),SC2(LJ,LI),
     *  SC3(LJ,LI),SC4(LJ,LI),SC5(LJ,LI),SC6(LJ,LI),SC7(LJ,LI),
     *  SC8(LJ,LI),SC9(LJ,LI),SCA(LJ,LI),SCB(LJ,LI),
     *  FPZ(LJ,LI),EMU(LJ,LI),EKT(LJ,LI)
      COMMON/DUMS/ STE(LJ,LI),STW(LJ,LI),STN(LJ,LI),STS(LJ,LI),
     1  SST1(LJ,LI),SST2(LJ,LI),SOUR(LJ,LI,6)
      DIMENSION TCPSP(LSP)
      SYM=DFLOAT(ISYM)
      HCONVR=GASC/WMSTR/HSTR
      HNORM=DFLOAT(LE)
      SPNORM=DFLOAT(LE)*DFLOAT(LSP-1)
      DO 10 I=1,LI
      DO J=1,LJ
      TKD=TK(J,I)*TSTR
      TKD2=TKD*TKD
      TKD3=TKD*TKD2
      TKD4=TKD*TKD3
      TKD5=TKD*TKD4
      IPOLY=1
      IF(TKD.GT.TPOL1) IPOLY=8
      TCP=0.0
      DO 11 ISP=1,LSP
      TCPSP(ISP)=(POLSP(IPOLY,ISP)+POLSP(IPOLY+1,ISP)*TKD
     1 +POLSP(IPOLY+2,ISP)*TKD2+POLSP(IPOLY+3,ISP)*TKD3
     2 +POLSP(IPOLY+4,ISP)*TKD4)/WM(ISP)
   11 CONTINUE
      TCPSP(  1)=TCPSP(  1)*FA0(J,I)
      TCPSP(  2)=TCPSP(  2)*FA1(J,I)
      TCPSP(  3)=TCPSP(  3)*FA2(J,I)
      TCPSP(  4)=TCPSP(  4)*FA3(J,I)
      TCPSP(  5)=TCPSP(  5)*FA4(J,I)
      TCPSP(  6)=TCPSP(  6)*FA5(J,I)
      TCPSP(  7)=TCPSP(  7)*FA6(J,I)
      TCPSP(  8)=TCPSP(  8)*FA7(J,I)
      TCPSP(  9)=TCPSP(  9)*FA8(J,I)
      TCPSP( 10)=TCPSP( 10)*FA9(J,I)
      TCPSP( 11)=TCPSP( 11)*FAA(J,I)
      TCPSP( 12)=TCPSP( 12)*FAB(J,I)
      TCPSP( 13)=TCPSP( 13)*FAC(J,I)
      TCPSP( 14)=TCPSP( 14)*FAD(J,I)
      TCPSP( 15)=TCPSP( 15)*FAE(J,I)
      TCPSP( 16)=TCPSP( 16)*FAF(J,I)
      TCPSP( 17)=TCPSP( 17)*FAG(J,I)
      TCPSP( 18)=TCPSP( 18)*FAH(J,I)
      TCPSP( 19)=TCPSP( 19)*FAI(J,I)
      TCPSP( 20)=TCPSP( 20)*FAJ(J,I)
      TCPSP( 21)=TCPSP( 21)*FB0(J,I)
      TCPSP( 22)=TCPSP( 22)*FB1(J,I)
      TCPSP( 23)=TCPSP( 23)*FB2(J,I)
      TCPSP( 24)=TCPSP( 24)*FB3(J,I)
      TCPSP( 25)=TCPSP( 25)*FB4(J,I)
      TCPSP( 26)=TCPSP( 26)*FB5(J,I)
      TCPSP( 27)=TCPSP( 27)*FB6(J,I)
      TCPSP( 28)=TCPSP( 28)*FB7(J,I)
      TCPSP( 29)=TCPSP( 29)*FB8(J,I)
      TCPSP( 30)=TCPSP( 30)*FB9(J,I)
      TCPSP( 31)=TCPSP( 31)*FBA(J,I)
      TCPSP( 32)=TCPSP( 32)*FBB(J,I)
      TCPSP( 33)=TCPSP( 33)*FBC(J,I)
      TCPSP( 34)=TCPSP( 34)*FBD(J,I)
      TCPSP( 35)=TCPSP( 35)*FBE(J,I)
      TCPSP( 36)=TCPSP( 36)*FBF(J,I)
      TCPSP( 37)=TCPSP( 37)*FBG(J,I)
      TCPSP( 38)=TCPSP( 38)*FBH(J,I)
      TCPSP( 39)=TCPSP( 39)*FBI(J,I)
      TCPSP( 40)=TCPSP( 40)*FBJ(J,I)
      TCPSP( 41)=TCPSP( 41)*FC0(J,I)
      TCPSP( 42)=TCPSP( 42)*FC1(J,I)
      TCPSP( 43)=TCPSP( 43)*FC2(J,I)
      TCPSP( 44)=TCPSP( 44)*FC3(J,I)
      TCPSP( 45)=TCPSP( 45)*FC4(J,I)
      TCPSP( 46)=TCPSP( 46)*FC5(J,I)
      TCPSP( 47)=TCPSP( 47)*FC6(J,I)
      TCPSP( 48)=TCPSP( 48)*FC7(J,I)
      TCPSP( 49)=TCPSP( 49)*FC8(J,I)
      TCPSP( 50)=TCPSP( 50)*FC9(J,I)
      TCPSP( 51)=TCPSP( 51)*FCA(J,I)
      TCPSP( 52)=TCPSP( 52)*FCB(J,I)
      TCP=0.0
      DO 12 ISP=1,LSP
      TCP=TCP+TCPSP(ISP)
   12 CONTINUE
      TCP=TCP/WMSTR*GASC*TSTR/HSTR
      EKT(J,I)=REI*(BETA2*VTC(J,I)/TCP+TMU(J,I)/SIGH)
      EMU(J,I)=REI*BETA3*RHO(J,I)
      FPZ(J,I)=HT(J,I)
      SST1(J,I)=STMF(J,I)
      SST2(J,I)=STND(J,I)
      SA0(J,I)=FA0(J,I)
      SA1(J,I)=FA1(J,I)
      SA2(J,I)=FA2(J,I)
      SA3(J,I)=FA3(J,I)
      SA4(J,I)=FA4(J,I)
      SA5(J,I)=FA5(J,I)
      SA6(J,I)=FA6(J,I)
      SA7(J,I)=FA7(J,I)
      SA8(J,I)=FA8(J,I)
      SA9(J,I)=FA9(J,I)
      SAA(J,I)=FAA(J,I)
      SAB(J,I)=FAB(J,I)
      SAC(J,I)=FAC(J,I)
      SAD(J,I)=FAD(J,I)
      SAE(J,I)=FAE(J,I)
      SAF(J,I)=FAF(J,I)
      SAG(J,I)=FAG(J,I)
      SAH(J,I)=FAH(J,I)
      SAI(J,I)=FAI(J,I)
      SAJ(J,I)=FAJ(J,I)
      SB0(J,I)=FB0(J,I)
      SB1(J,I)=FB1(J,I)
      SB2(J,I)=FB2(J,I)
      SB3(J,I)=FB3(J,I)
      SB4(J,I)=FB4(J,I)
      SB5(J,I)=FB5(J,I)
      SB6(J,I)=FB6(J,I)
      SB7(J,I)=FB7(J,I)
      SB8(J,I)=FB8(J,I)
      SB9(J,I)=FB9(J,I)
      SBA(J,I)=FBA(J,I)
      SBB(J,I)=FBB(J,I)
      SBC(J,I)=FBC(J,I)
      SBD(J,I)=FBD(J,I)
      SBE(J,I)=FBE(J,I)
      SBF(J,I)=FBF(J,I)
      SBG(J,I)=FBG(J,I)
      SBH(J,I)=FBH(J,I)
      SBI(J,I)=FBI(J,I)
      SBJ(J,I)=FBJ(J,I)
      SC0(J,I)=FC0(J,I)
      SC1(J,I)=FC1(J,I)
      SC2(J,I)=FC2(J,I)
      SC3(J,I)=FC3(J,I)
      SC4(J,I)=FC4(J,I)
      SC5(J,I)=FC5(J,I)
      SC6(J,I)=FC6(J,I)
      SC7(J,I)=FC7(J,I)
      SC8(J,I)=FC8(J,I)
      SC9(J,I)=FC9(J,I)
      SCA(J,I)=FCA(J,I)
      SCB(J,I)=FCB(J,I)
      ENDDO
   10 CONTINUE
      DO 14 I=2,LI
      DO J=2,LJ
      M=I-1
      N=J-1
      TURS=REI*(TMU(J,I)+TMU(N,I))/SIGSP
      TURW=REI*(TMU(J,I)+TMU(J,M))/SIGSP
C-----------------------------------------------------------------------
      ZS(J,I)=(EKT(J,I)+EKT(N,I))/YYS(J)
      STS(J,I)=(EMU(J,I)*STDF(J,I)+EMU(N,I)*STDF(N,I)+TURS)/YYS(J)
      QA0(J,I)=(EMU(J,I)*VDF(J,I,  1)+EMU(N,I)*VDF(N,I,  1)+TURS)/YYS(J)
      QA1(J,I)=(EMU(J,I)*VDF(J,I,  2)+EMU(N,I)*VDF(N,I,  2)+TURS)/YYS(J)
      QA2(J,I)=(EMU(J,I)*VDF(J,I,  3)+EMU(N,I)*VDF(N,I,  3)+TURS)/YYS(J)
      QA3(J,I)=(EMU(J,I)*VDF(J,I,  4)+EMU(N,I)*VDF(N,I,  4)+TURS)/YYS(J)
      QA4(J,I)=(EMU(J,I)*VDF(J,I,  5)+EMU(N,I)*VDF(N,I,  5)+TURS)/YYS(J)
      QA5(J,I)=(EMU(J,I)*VDF(J,I,  6)+EMU(N,I)*VDF(N,I,  6)+TURS)/YYS(J)
      QA6(J,I)=(EMU(J,I)*VDF(J,I,  7)+EMU(N,I)*VDF(N,I,  7)+TURS)/YYS(J)
      QA7(J,I)=(EMU(J,I)*VDF(J,I,  8)+EMU(N,I)*VDF(N,I,  8)+TURS)/YYS(J)
      QA8(J,I)=(EMU(J,I)*VDF(J,I,  9)+EMU(N,I)*VDF(N,I,  9)+TURS)/YYS(J)
      QA9(J,I)=(EMU(J,I)*VDF(J,I, 10)+EMU(N,I)*VDF(N,I, 10)+TURS)/YYS(J)
      QAA(J,I)=(EMU(J,I)*VDF(J,I, 11)+EMU(N,I)*VDF(N,I, 11)+TURS)/YYS(J)
      QAB(J,I)=(EMU(J,I)*VDF(J,I, 12)+EMU(N,I)*VDF(N,I, 12)+TURS)/YYS(J)
      QAC(J,I)=(EMU(J,I)*VDF(J,I, 13)+EMU(N,I)*VDF(N,I, 13)+TURS)/YYS(J)
      QAD(J,I)=(EMU(J,I)*VDF(J,I, 14)+EMU(N,I)*VDF(N,I, 14)+TURS)/YYS(J)
      QAE(J,I)=(EMU(J,I)*VDF(J,I, 15)+EMU(N,I)*VDF(N,I, 15)+TURS)/YYS(J)
      QAF(J,I)=(EMU(J,I)*VDF(J,I, 16)+EMU(N,I)*VDF(N,I, 16)+TURS)/YYS(J)
      QAG(J,I)=(EMU(J,I)*VDF(J,I, 17)+EMU(N,I)*VDF(N,I, 17)+TURS)/YYS(J)
      QAH(J,I)=(EMU(J,I)*VDF(J,I, 18)+EMU(N,I)*VDF(N,I, 18)+TURS)/YYS(J)
      QAI(J,I)=(EMU(J,I)*VDF(J,I, 19)+EMU(N,I)*VDF(N,I, 19)+TURS)/YYS(J)
      QAJ(J,I)=(EMU(J,I)*VDF(J,I, 20)+EMU(N,I)*VDF(N,I, 20)+TURS)/YYS(J)
      QB0(J,I)=(EMU(J,I)*VDF(J,I, 21)+EMU(N,I)*VDF(N,I, 21)+TURS)/YYS(J)
      QB1(J,I)=(EMU(J,I)*VDF(J,I, 22)+EMU(N,I)*VDF(N,I, 22)+TURS)/YYS(J)
      QB2(J,I)=(EMU(J,I)*VDF(J,I, 23)+EMU(N,I)*VDF(N,I, 23)+TURS)/YYS(J)
      QB3(J,I)=(EMU(J,I)*VDF(J,I, 24)+EMU(N,I)*VDF(N,I, 24)+TURS)/YYS(J)
      QB4(J,I)=(EMU(J,I)*VDF(J,I, 25)+EMU(N,I)*VDF(N,I, 25)+TURS)/YYS(J)
      QB5(J,I)=(EMU(J,I)*VDF(J,I, 26)+EMU(N,I)*VDF(N,I, 26)+TURS)/YYS(J)
      QB6(J,I)=(EMU(J,I)*VDF(J,I, 27)+EMU(N,I)*VDF(N,I, 27)+TURS)/YYS(J)
      QB7(J,I)=(EMU(J,I)*VDF(J,I, 28)+EMU(N,I)*VDF(N,I, 28)+TURS)/YYS(J)
      QB8(J,I)=(EMU(J,I)*VDF(J,I, 29)+EMU(N,I)*VDF(N,I, 29)+TURS)/YYS(J)
      QB9(J,I)=(EMU(J,I)*VDF(J,I, 30)+EMU(N,I)*VDF(N,I, 30)+TURS)/YYS(J)
      QBA(J,I)=(EMU(J,I)*VDF(J,I, 31)+EMU(N,I)*VDF(N,I, 31)+TURS)/YYS(J)
      QBB(J,I)=(EMU(J,I)*VDF(J,I, 32)+EMU(N,I)*VDF(N,I, 32)+TURS)/YYS(J)
      QBC(J,I)=(EMU(J,I)*VDF(J,I, 33)+EMU(N,I)*VDF(N,I, 33)+TURS)/YYS(J)
      QBD(J,I)=(EMU(J,I)*VDF(J,I, 34)+EMU(N,I)*VDF(N,I, 34)+TURS)/YYS(J)
      QBE(J,I)=(EMU(J,I)*VDF(J,I, 35)+EMU(N,I)*VDF(N,I, 35)+TURS)/YYS(J)
      QBF(J,I)=(EMU(J,I)*VDF(J,I, 36)+EMU(N,I)*VDF(N,I, 36)+TURS)/YYS(J)
      QBG(J,I)=(EMU(J,I)*VDF(J,I, 37)+EMU(N,I)*VDF(N,I, 37)+TURS)/YYS(J)
      QBH(J,I)=(EMU(J,I)*VDF(J,I, 38)+EMU(N,I)*VDF(N,I, 38)+TURS)/YYS(J)
      QBI(J,I)=(EMU(J,I)*VDF(J,I, 39)+EMU(N,I)*VDF(N,I, 39)+TURS)/YYS(J)
      QBJ(J,I)=(EMU(J,I)*VDF(J,I, 40)+EMU(N,I)*VDF(N,I, 40)+TURS)/YYS(J)
      QC0(J,I)=(EMU(J,I)*VDF(J,I, 41)+EMU(N,I)*VDF(N,I, 41)+TURS)/YYS(J)
      QC1(J,I)=(EMU(J,I)*VDF(J,I, 42)+EMU(N,I)*VDF(N,I, 42)+TURS)/YYS(J)
      QC2(J,I)=(EMU(J,I)*VDF(J,I, 43)+EMU(N,I)*VDF(N,I, 43)+TURS)/YYS(J)
      QC3(J,I)=(EMU(J,I)*VDF(J,I, 44)+EMU(N,I)*VDF(N,I, 44)+TURS)/YYS(J)
      QC4(J,I)=(EMU(J,I)*VDF(J,I, 45)+EMU(N,I)*VDF(N,I, 45)+TURS)/YYS(J)
      QC5(J,I)=(EMU(J,I)*VDF(J,I, 46)+EMU(N,I)*VDF(N,I, 46)+TURS)/YYS(J)
      QC6(J,I)=(EMU(J,I)*VDF(J,I, 47)+EMU(N,I)*VDF(N,I, 47)+TURS)/YYS(J)
      QC7(J,I)=(EMU(J,I)*VDF(J,I, 48)+EMU(N,I)*VDF(N,I, 48)+TURS)/YYS(J)
      QC8(J,I)=(EMU(J,I)*VDF(J,I, 49)+EMU(N,I)*VDF(N,I, 49)+TURS)/YYS(J)
      QC9(J,I)=(EMU(J,I)*VDF(J,I, 50)+EMU(N,I)*VDF(N,I, 50)+TURS)/YYS(J)
      QCA(J,I)=(EMU(J,I)*VDF(J,I, 51)+EMU(N,I)*VDF(N,I, 51)+TURS)/YYS(J)
C-----------------------------------------------------------------------
      ZW(J,I)=(EKT(J,I)+EKT(J,M))/XXS(I)
      STW(J,I)=(EMU(J,I)*STDF(J,I)+EMU(J,M)*STDF(J,M)+TURW)/XXS(I)
      WA0(J,I)=(EMU(J,I)*VDF(J,I,  1)+EMU(J,M)*VDF(J,M,  1)+TURW)/XXS(I)
      WA1(J,I)=(EMU(J,I)*VDF(J,I,  2)+EMU(J,M)*VDF(J,M,  2)+TURW)/XXS(I)
      WA2(J,I)=(EMU(J,I)*VDF(J,I,  3)+EMU(J,M)*VDF(J,M,  3)+TURW)/XXS(I)
      WA3(J,I)=(EMU(J,I)*VDF(J,I,  4)+EMU(J,M)*VDF(J,M,  4)+TURW)/XXS(I)
      WA4(J,I)=(EMU(J,I)*VDF(J,I,  5)+EMU(J,M)*VDF(J,M,  5)+TURW)/XXS(I)
      WA5(J,I)=(EMU(J,I)*VDF(J,I,  6)+EMU(J,M)*VDF(J,M,  6)+TURW)/XXS(I)
      WA6(J,I)=(EMU(J,I)*VDF(J,I,  7)+EMU(J,M)*VDF(J,M,  7)+TURW)/XXS(I)
      WA7(J,I)=(EMU(J,I)*VDF(J,I,  8)+EMU(J,M)*VDF(J,M,  8)+TURW)/XXS(I)
      WA8(J,I)=(EMU(J,I)*VDF(J,I,  9)+EMU(J,M)*VDF(J,M,  9)+TURW)/XXS(I)
      WA9(J,I)=(EMU(J,I)*VDF(J,I, 10)+EMU(J,M)*VDF(J,M, 10)+TURW)/XXS(I)
      WAA(J,I)=(EMU(J,I)*VDF(J,I, 11)+EMU(J,M)*VDF(J,M, 11)+TURW)/XXS(I)
      WAB(J,I)=(EMU(J,I)*VDF(J,I, 12)+EMU(J,M)*VDF(J,M, 12)+TURW)/XXS(I)
      WAC(J,I)=(EMU(J,I)*VDF(J,I, 13)+EMU(J,M)*VDF(J,M, 13)+TURW)/XXS(I)
      WAD(J,I)=(EMU(J,I)*VDF(J,I, 14)+EMU(J,M)*VDF(J,M, 14)+TURW)/XXS(I)
      WAE(J,I)=(EMU(J,I)*VDF(J,I, 15)+EMU(J,M)*VDF(J,M, 15)+TURW)/XXS(I)
      WAF(J,I)=(EMU(J,I)*VDF(J,I, 16)+EMU(J,M)*VDF(J,M, 16)+TURW)/XXS(I)
      WAG(J,I)=(EMU(J,I)*VDF(J,I, 17)+EMU(J,M)*VDF(J,M, 17)+TURW)/XXS(I)
      WAH(J,I)=(EMU(J,I)*VDF(J,I, 18)+EMU(J,M)*VDF(J,M, 18)+TURW)/XXS(I)
      WAI(J,I)=(EMU(J,I)*VDF(J,I, 19)+EMU(J,M)*VDF(J,M, 19)+TURW)/XXS(I)
      WAJ(J,I)=(EMU(J,I)*VDF(J,I, 20)+EMU(J,M)*VDF(J,M, 20)+TURW)/XXS(I)
      WB0(J,I)=(EMU(J,I)*VDF(J,I, 21)+EMU(J,M)*VDF(J,M, 21)+TURW)/XXS(I)
      WB1(J,I)=(EMU(J,I)*VDF(J,I, 22)+EMU(J,M)*VDF(J,M, 22)+TURW)/XXS(I)
      WB2(J,I)=(EMU(J,I)*VDF(J,I, 23)+EMU(J,M)*VDF(J,M, 23)+TURW)/XXS(I)
      WB3(J,I)=(EMU(J,I)*VDF(J,I, 24)+EMU(J,M)*VDF(J,M, 24)+TURW)/XXS(I)
      WB4(J,I)=(EMU(J,I)*VDF(J,I, 25)+EMU(J,M)*VDF(J,M, 25)+TURW)/XXS(I)
      WB5(J,I)=(EMU(J,I)*VDF(J,I, 26)+EMU(J,M)*VDF(J,M, 26)+TURW)/XXS(I)
      WB6(J,I)=(EMU(J,I)*VDF(J,I, 27)+EMU(J,M)*VDF(J,M, 27)+TURW)/XXS(I)
      WB7(J,I)=(EMU(J,I)*VDF(J,I, 28)+EMU(J,M)*VDF(J,M, 28)+TURW)/XXS(I)
      WB8(J,I)=(EMU(J,I)*VDF(J,I, 29)+EMU(J,M)*VDF(J,M, 29)+TURW)/XXS(I)
      WB9(J,I)=(EMU(J,I)*VDF(J,I, 30)+EMU(J,M)*VDF(J,M, 30)+TURW)/XXS(I)
      WBA(J,I)=(EMU(J,I)*VDF(J,I, 31)+EMU(J,M)*VDF(J,M, 31)+TURW)/XXS(I)
      WBB(J,I)=(EMU(J,I)*VDF(J,I, 32)+EMU(J,M)*VDF(J,M, 32)+TURW)/XXS(I)
      WBC(J,I)=(EMU(J,I)*VDF(J,I, 33)+EMU(J,M)*VDF(J,M, 33)+TURW)/XXS(I)
      WBD(J,I)=(EMU(J,I)*VDF(J,I, 34)+EMU(J,M)*VDF(J,M, 34)+TURW)/XXS(I)
      WBE(J,I)=(EMU(J,I)*VDF(J,I, 35)+EMU(J,M)*VDF(J,M, 35)+TURW)/XXS(I)
      WBF(J,I)=(EMU(J,I)*VDF(J,I, 36)+EMU(J,M)*VDF(J,M, 36)+TURW)/XXS(I)
      WBG(J,I)=(EMU(J,I)*VDF(J,I, 37)+EMU(J,M)*VDF(J,M, 37)+TURW)/XXS(I)
      WBH(J,I)=(EMU(J,I)*VDF(J,I, 38)+EMU(J,M)*VDF(J,M, 38)+TURW)/XXS(I)
      WBI(J,I)=(EMU(J,I)*VDF(J,I, 39)+EMU(J,M)*VDF(J,M, 39)+TURW)/XXS(I)
      WBJ(J,I)=(EMU(J,I)*VDF(J,I, 40)+EMU(J,M)*VDF(J,M, 40)+TURW)/XXS(I)
      WC0(J,I)=(EMU(J,I)*VDF(J,I, 41)+EMU(J,M)*VDF(J,M, 41)+TURW)/XXS(I)
      WC1(J,I)=(EMU(J,I)*VDF(J,I, 42)+EMU(J,M)*VDF(J,M, 42)+TURW)/XXS(I)
      WC2(J,I)=(EMU(J,I)*VDF(J,I, 43)+EMU(J,M)*VDF(J,M, 43)+TURW)/XXS(I)
      WC3(J,I)=(EMU(J,I)*VDF(J,I, 44)+EMU(J,M)*VDF(J,M, 44)+TURW)/XXS(I)
      WC4(J,I)=(EMU(J,I)*VDF(J,I, 45)+EMU(J,M)*VDF(J,M, 45)+TURW)/XXS(I)
      WC5(J,I)=(EMU(J,I)*VDF(J,I, 46)+EMU(J,M)*VDF(J,M, 46)+TURW)/XXS(I)
      WC6(J,I)=(EMU(J,I)*VDF(J,I, 47)+EMU(J,M)*VDF(J,M, 47)+TURW)/XXS(I)
      WC7(J,I)=(EMU(J,I)*VDF(J,I, 48)+EMU(J,M)*VDF(J,M, 48)+TURW)/XXS(I)
      WC8(J,I)=(EMU(J,I)*VDF(J,I, 49)+EMU(J,M)*VDF(J,M, 49)+TURW)/XXS(I)
      WC9(J,I)=(EMU(J,I)*VDF(J,I, 50)+EMU(J,M)*VDF(J,M, 50)+TURW)/XXS(I)
      WCA(J,I)=(EMU(J,I)*VDF(J,I, 51)+EMU(J,M)*VDF(J,M, 51)+TURW)/XXS(I)
      ENDDO
   14 CONTINUE
C-----------------------------COEFFICIENTS------------------------------
      DO 20 I=2,LI-1
      DO J=2,LJ-1
      IF(ISKIP(J,I).GE.10) GO TO 21
      DXE=XXS(I+1)
      DXW=XXS(I)
      DXCP=XXC(I)
C
      DYN=YYS(J+1)
      DYS=YYS(J)
      DYCP=YYC(J)
C
      DTBRX=DT/DXCP
      DTBRY=DT/DYCP
      RHOUE=0.5*(RHO(J,I+1)+RHO(J,I))*U(J,I+1)
      RHOUW=0.5*(RHO(J,I)+RHO(J,I-1))*U(J,I)
      RHOVN=0.5*(RHO(J+1,I)+RHO(J,I))*V(J+1,I)
      RHOVS=0.5*(RHO(J,I)+RHO(J-1,I))*V(J,I)
C-----------------------------------------------------------------------
      SYMZ=SYM*DT*0.5*EKT(J,I)/Y(J,I)
      SYM1=SYM*DT*0.5*EMU(J,I)/Y(J,I)
      SYM2=SYM*DT*0.5*REI*TMU(J,I)/SIGSP/Y(J,I)
      SYMST=SYM1*STDF(J,I)+SYM2
      SYMA0=SYM1*VDF(J,I,  1)+SYM2
      SYMA1=SYM1*VDF(J,I,  2)+SYM2
      SYMA2=SYM1*VDF(J,I,  3)+SYM2
      SYMA3=SYM1*VDF(J,I,  4)+SYM2
      SYMA4=SYM1*VDF(J,I,  5)+SYM2
      SYMA5=SYM1*VDF(J,I,  6)+SYM2
      SYMA6=SYM1*VDF(J,I,  7)+SYM2
      SYMA7=SYM1*VDF(J,I,  8)+SYM2
      SYMA8=SYM1*VDF(J,I,  9)+SYM2
      SYMA9=SYM1*VDF(J,I, 10)+SYM2
      SYMAA=SYM1*VDF(J,I, 11)+SYM2
      SYMAB=SYM1*VDF(J,I, 12)+SYM2
      SYMAC=SYM1*VDF(J,I, 13)+SYM2
      SYMAD=SYM1*VDF(J,I, 14)+SYM2
      SYMAE=SYM1*VDF(J,I, 15)+SYM2
      SYMAF=SYM1*VDF(J,I, 16)+SYM2
      SYMAG=SYM1*VDF(J,I, 17)+SYM2
      SYMAH=SYM1*VDF(J,I, 18)+SYM2
      SYMAI=SYM1*VDF(J,I, 19)+SYM2
      SYMAJ=SYM1*VDF(J,I, 20)+SYM2
      SYMB0=SYM1*VDF(J,I, 21)+SYM2
      SYMB1=SYM1*VDF(J,I, 22)+SYM2
      SYMB2=SYM1*VDF(J,I, 23)+SYM2
      SYMB3=SYM1*VDF(J,I, 24)+SYM2
      SYMB4=SYM1*VDF(J,I, 25)+SYM2
      SYMB5=SYM1*VDF(J,I, 26)+SYM2
      SYMB6=SYM1*VDF(J,I, 27)+SYM2
      SYMB7=SYM1*VDF(J,I, 28)+SYM2
      SYMB8=SYM1*VDF(J,I, 29)+SYM2
      SYMB9=SYM1*VDF(J,I, 30)+SYM2
      SYMBA=SYM1*VDF(J,I, 31)+SYM2
      SYMBB=SYM1*VDF(J,I, 32)+SYM2
      SYMBC=SYM1*VDF(J,I, 33)+SYM2
      SYMBD=SYM1*VDF(J,I, 34)+SYM2
      SYMBE=SYM1*VDF(J,I, 35)+SYM2
      SYMBF=SYM1*VDF(J,I, 36)+SYM2
      SYMBG=SYM1*VDF(J,I, 37)+SYM2
      SYMBH=SYM1*VDF(J,I, 38)+SYM2
      SYMBI=SYM1*VDF(J,I, 39)+SYM2
      SYMBJ=SYM1*VDF(J,I, 40)+SYM2
      SYMC0=SYM1*VDF(J,I, 41)+SYM2
      SYMC1=SYM1*VDF(J,I, 42)+SYM2
      SYMC2=SYM1*VDF(J,I, 43)+SYM2
      SYMC3=SYM1*VDF(J,I, 44)+SYM2
      SYMC4=SYM1*VDF(J,I, 45)+SYM2
      SYMC5=SYM1*VDF(J,I, 46)+SYM2
      SYMC6=SYM1*VDF(J,I, 47)+SYM2
      SYMC7=SYM1*VDF(J,I, 48)+SYM2
      SYMC8=SYM1*VDF(J,I, 49)+SYM2
      SYMC9=SYM1*VDF(J,I, 50)+SYM2
      SYMCA=SYM1*VDF(J,I, 51)+SYM2
C-----------------------------------------------------------------------
      ZCONV=DABS(RHOUE)
      STCONV=ZCONV
      A0CONV=ZCONV
      A1CONV=ZCONV
      A2CONV=ZCONV
      A3CONV=ZCONV
      A4CONV=ZCONV
      A5CONV=ZCONV
      A6CONV=ZCONV
      A7CONV=ZCONV
      A8CONV=ZCONV
      A9CONV=ZCONV
      AACONV=ZCONV
      ABCONV=ZCONV
      ACCONV=ZCONV
      ADCONV=ZCONV
      AECONV=ZCONV
      AFCONV=ZCONV
      AGCONV=ZCONV
      AHCONV=ZCONV
      AICONV=ZCONV
      AJCONV=ZCONV
      B0CONV=ZCONV
      B1CONV=ZCONV
      B2CONV=ZCONV
      B3CONV=ZCONV
      B4CONV=ZCONV
      B5CONV=ZCONV
      B6CONV=ZCONV
      B7CONV=ZCONV
      B8CONV=ZCONV
      B9CONV=ZCONV
      BACONV=ZCONV
      BBCONV=ZCONV
      BCCONV=ZCONV
      BDCONV=ZCONV
      BECONV=ZCONV
      BFCONV=ZCONV
      BGCONV=ZCONV
      BHCONV=ZCONV
      BICONV=ZCONV
      BJCONV=ZCONV
      C0CONV=ZCONV
      C1CONV=ZCONV
      C2CONV=ZCONV
      C3CONV=ZCONV
      C4CONV=ZCONV
      C5CONV=ZCONV
      C6CONV=ZCONV
      C7CONV=ZCONV
      C8CONV=ZCONV
      C9CONV=ZCONV
      CACONV=ZCONV
C-----------------------------------------------------------------------
      ZDIFU=ZW(J,I+1)
      STDIFU=STW(J,I+1)
      A0DIFU=WA0(J,I+1)
      A1DIFU=WA1(J,I+1)
      A2DIFU=WA2(J,I+1)
      A3DIFU=WA3(J,I+1)
      A4DIFU=WA4(J,I+1)
      A5DIFU=WA5(J,I+1)
      A6DIFU=WA6(J,I+1)
      A7DIFU=WA7(J,I+1)
      A8DIFU=WA8(J,I+1)
      A9DIFU=WA9(J,I+1)
      AADIFU=WAA(J,I+1)
      ABDIFU=WAB(J,I+1)
      ACDIFU=WAC(J,I+1)
      ADDIFU=WAD(J,I+1)
      AEDIFU=WAE(J,I+1)
      AFDIFU=WAF(J,I+1)
      AGDIFU=WAG(J,I+1)
      AHDIFU=WAH(J,I+1)
      AIDIFU=WAI(J,I+1)
      AJDIFU=WAJ(J,I+1)
      B0DIFU=WB0(J,I+1)
      B1DIFU=WB1(J,I+1)
      B2DIFU=WB2(J,I+1)
      B3DIFU=WB3(J,I+1)
      B4DIFU=WB4(J,I+1)
      B5DIFU=WB5(J,I+1)
      B6DIFU=WB6(J,I+1)
      B7DIFU=WB7(J,I+1)
      B8DIFU=WB8(J,I+1)
      B9DIFU=WB9(J,I+1)
      BADIFU=WBA(J,I+1)
      BBDIFU=WBB(J,I+1)
      BCDIFU=WBC(J,I+1)
      BDDIFU=WBD(J,I+1)
      BEDIFU=WBE(J,I+1)
      BFDIFU=WBF(J,I+1)
      BGDIFU=WBG(J,I+1)
      BHDIFU=WBH(J,I+1)
      BIDIFU=WBI(J,I+1)
      BJDIFU=WBJ(J,I+1)
      C0DIFU=WC0(J,I+1)
      C1DIFU=WC1(J,I+1)
      C2DIFU=WC2(J,I+1)
      C3DIFU=WC3(J,I+1)
      C4DIFU=WC4(J,I+1)
      C5DIFU=WC5(J,I+1)
      C6DIFU=WC6(J,I+1)
      C7DIFU=WC7(J,I+1)
      C8DIFU=WC8(J,I+1)
      C9DIFU=WC9(J,I+1)
      CADIFU=WCA(J,I+1)
C-----------------------------------------------------------------------
      IF(ZDIFU.GE.ZCONV) ZCONV=ZDIFU
      IF(STDIFU.GE.STCONV) STCONV=STDIFU
      IF(A0DIFU.GE.A0CONV) A0CONV=A0DIFU
      IF(A1DIFU.GE.A1CONV) A1CONV=A1DIFU
      IF(A2DIFU.GE.A2CONV) A2CONV=A2DIFU
      IF(A3DIFU.GE.A3CONV) A3CONV=A3DIFU
      IF(A4DIFU.GE.A4CONV) A4CONV=A4DIFU
      IF(A5DIFU.GE.A5CONV) A5CONV=A5DIFU
      IF(A6DIFU.GE.A6CONV) A6CONV=A6DIFU
      IF(A7DIFU.GE.A7CONV) A7CONV=A7DIFU
      IF(A8DIFU.GE.A8CONV) A8CONV=A8DIFU
      IF(A9DIFU.GE.A9CONV) A9CONV=A9DIFU
      IF(AADIFU.GE.AACONV) AACONV=AADIFU
      IF(ABDIFU.GE.ABCONV) ABCONV=ABDIFU
      IF(ACDIFU.GE.ACCONV) ACCONV=ACDIFU
      IF(ADDIFU.GE.ADCONV) ADCONV=ADDIFU
      IF(AEDIFU.GE.AECONV) AECONV=AEDIFU
      IF(AFDIFU.GE.AFCONV) AFCONV=AFDIFU
      IF(AGDIFU.GE.AGCONV) AGCONV=AGDIFU
      IF(AHDIFU.GE.AHCONV) AHCONV=AHDIFU
      IF(AIDIFU.GE.AICONV) AICONV=AIDIFU
      IF(AJDIFU.GE.AJCONV) AJCONV=AJDIFU
      IF(B0DIFU.GE.B0CONV) B0CONV=B0DIFU
      IF(B1DIFU.GE.B1CONV) B1CONV=B1DIFU
      IF(B2DIFU.GE.B2CONV) B2CONV=B2DIFU
      IF(B3DIFU.GE.B3CONV) B3CONV=B3DIFU
      IF(B4DIFU.GE.B4CONV) B4CONV=B4DIFU
      IF(B5DIFU.GE.B5CONV) B5CONV=B5DIFU
      IF(B6DIFU.GE.B6CONV) B6CONV=B6DIFU
      IF(B7DIFU.GE.B7CONV) B7CONV=B7DIFU
      IF(B8DIFU.GE.B8CONV) B8CONV=B8DIFU
      IF(B9DIFU.GE.B9CONV) B9CONV=B9DIFU
      IF(BADIFU.GE.BACONV) BACONV=BADIFU
      IF(BBDIFU.GE.BBCONV) BBCONV=BBDIFU
      IF(BCDIFU.GE.BCCONV) BCCONV=BCDIFU
      IF(BDDIFU.GE.BDCONV) BDCONV=BDDIFU
      IF(BEDIFU.GE.BECONV) BECONV=BEDIFU
      IF(BFDIFU.GE.BFCONV) BFCONV=BFDIFU
      IF(BGDIFU.GE.BGCONV) BGCONV=BGDIFU
      IF(BHDIFU.GE.BHCONV) BHCONV=BHDIFU
      IF(BIDIFU.GE.BICONV) BICONV=BIDIFU
      IF(BJDIFU.GE.BJCONV) BJCONV=BJDIFU
      IF(C0DIFU.GE.C0CONV) C0CONV=C0DIFU
      IF(C1DIFU.GE.C1CONV) C1CONV=C1DIFU
      IF(C2DIFU.GE.C2CONV) C2CONV=C2DIFU
      IF(C3DIFU.GE.C3CONV) C3CONV=C3DIFU
      IF(C4DIFU.GE.C4CONV) C4CONV=C4DIFU
      IF(C5DIFU.GE.C5CONV) C5CONV=C5DIFU
      IF(C6DIFU.GE.C6CONV) C6CONV=C6DIFU
      IF(C7DIFU.GE.C7CONV) C7CONV=C7DIFU
      IF(C8DIFU.GE.C8CONV) C8CONV=C8DIFU
      IF(C9DIFU.GE.C9CONV) C9CONV=C9DIFU
      IF(CADIFU.GE.CACONV) CACONV=CADIFU
C-----------------------------------------------------------------------
      ZE(J,I)=DTBRX*0.5*(RHOUE-ZCONV)
      STE(J,I)=DTBRX*0.5*(RHOUE-STCONV)
      EA0(J,I)=DTBRX*0.5*(RHOUE-A0CONV)
      EA1(J,I)=DTBRX*0.5*(RHOUE-A1CONV)
      EA2(J,I)=DTBRX*0.5*(RHOUE-A2CONV)
      EA3(J,I)=DTBRX*0.5*(RHOUE-A3CONV)
      EA4(J,I)=DTBRX*0.5*(RHOUE-A4CONV)
      EA5(J,I)=DTBRX*0.5*(RHOUE-A5CONV)
      EA6(J,I)=DTBRX*0.5*(RHOUE-A6CONV)
      EA7(J,I)=DTBRX*0.5*(RHOUE-A7CONV)
      EA8(J,I)=DTBRX*0.5*(RHOUE-A8CONV)
      EA9(J,I)=DTBRX*0.5*(RHOUE-A9CONV)
      EAA(J,I)=DTBRX*0.5*(RHOUE-AACONV)
      EAB(J,I)=DTBRX*0.5*(RHOUE-ABCONV)
      EAC(J,I)=DTBRX*0.5*(RHOUE-ACCONV)
      EAD(J,I)=DTBRX*0.5*(RHOUE-ADCONV)
      EAE(J,I)=DTBRX*0.5*(RHOUE-AECONV)
      EAF(J,I)=DTBRX*0.5*(RHOUE-AFCONV)
      EAG(J,I)=DTBRX*0.5*(RHOUE-AGCONV)
      EAH(J,I)=DTBRX*0.5*(RHOUE-AHCONV)
      EAI(J,I)=DTBRX*0.5*(RHOUE-AICONV)
      EAJ(J,I)=DTBRX*0.5*(RHOUE-AJCONV)
      EB0(J,I)=DTBRX*0.5*(RHOUE-B0CONV)
      EB1(J,I)=DTBRX*0.5*(RHOUE-B1CONV)
      EB2(J,I)=DTBRX*0.5*(RHOUE-B2CONV)
      EB3(J,I)=DTBRX*0.5*(RHOUE-B3CONV)
      EB4(J,I)=DTBRX*0.5*(RHOUE-B4CONV)
      EB5(J,I)=DTBRX*0.5*(RHOUE-B5CONV)
      EB6(J,I)=DTBRX*0.5*(RHOUE-B6CONV)
      EB7(J,I)=DTBRX*0.5*(RHOUE-B7CONV)
      EB8(J,I)=DTBRX*0.5*(RHOUE-B8CONV)
      EB9(J,I)=DTBRX*0.5*(RHOUE-B9CONV)
      EBA(J,I)=DTBRX*0.5*(RHOUE-BACONV)
      EBB(J,I)=DTBRX*0.5*(RHOUE-BBCONV)
      EBC(J,I)=DTBRX*0.5*(RHOUE-BCCONV)
      EBD(J,I)=DTBRX*0.5*(RHOUE-BDCONV)
      EBE(J,I)=DTBRX*0.5*(RHOUE-BECONV)
      EBF(J,I)=DTBRX*0.5*(RHOUE-BFCONV)
      EBG(J,I)=DTBRX*0.5*(RHOUE-BGCONV)
      EBH(J,I)=DTBRX*0.5*(RHOUE-BHCONV)
      EBI(J,I)=DTBRX*0.5*(RHOUE-BICONV)
      EBJ(J,I)=DTBRX*0.5*(RHOUE-BJCONV)
      EC0(J,I)=DTBRX*0.5*(RHOUE-C0CONV)
      EC1(J,I)=DTBRX*0.5*(RHOUE-C1CONV)
      EC2(J,I)=DTBRX*0.5*(RHOUE-C2CONV)
      EC3(J,I)=DTBRX*0.5*(RHOUE-C3CONV)
      EC4(J,I)=DTBRX*0.5*(RHOUE-C4CONV)
      EC5(J,I)=DTBRX*0.5*(RHOUE-C5CONV)
      EC6(J,I)=DTBRX*0.5*(RHOUE-C6CONV)
      EC7(J,I)=DTBRX*0.5*(RHOUE-C7CONV)
      EC8(J,I)=DTBRX*0.5*(RHOUE-C8CONV)
      EC9(J,I)=DTBRX*0.5*(RHOUE-C9CONV)
      ECA(J,I)=DTBRX*0.5*(RHOUE-CACONV)
C-----------------------------------------------------------------------
      ZCONV=DABS(RHOUW)
      STCONV=ZCONV
      A0CONV=ZCONV
      A1CONV=ZCONV
      A2CONV=ZCONV
      A3CONV=ZCONV
      A4CONV=ZCONV
      A5CONV=ZCONV
      A6CONV=ZCONV
      A7CONV=ZCONV
      A8CONV=ZCONV
      A9CONV=ZCONV
      AACONV=ZCONV
      ABCONV=ZCONV
      ACCONV=ZCONV
      ADCONV=ZCONV
      AECONV=ZCONV
      AFCONV=ZCONV
      AGCONV=ZCONV
      AHCONV=ZCONV
      AICONV=ZCONV
      AJCONV=ZCONV
      B0CONV=ZCONV
      B1CONV=ZCONV
      B2CONV=ZCONV
      B3CONV=ZCONV
      B4CONV=ZCONV
      B5CONV=ZCONV
      B6CONV=ZCONV
      B7CONV=ZCONV
      B8CONV=ZCONV
      B9CONV=ZCONV
      BACONV=ZCONV
      BBCONV=ZCONV
      BCCONV=ZCONV
      BDCONV=ZCONV
      BECONV=ZCONV
      BFCONV=ZCONV
      BGCONV=ZCONV
      BHCONV=ZCONV
      BICONV=ZCONV
      BJCONV=ZCONV
      C0CONV=ZCONV
      C1CONV=ZCONV
      C2CONV=ZCONV
      C3CONV=ZCONV
      C4CONV=ZCONV
      C5CONV=ZCONV
      C6CONV=ZCONV
      C7CONV=ZCONV
      C8CONV=ZCONV
      C9CONV=ZCONV
      CACONV=ZCONV
C-----------------------------------------------------------------------
      ZDIFU=ZW(J,I)
      STDIFU=STW(J,I)
      A0DIFU=WA0(J,I)
      A1DIFU=WA1(J,I)
      A2DIFU=WA2(J,I)
      A3DIFU=WA3(J,I)
      A4DIFU=WA4(J,I)
      A5DIFU=WA5(J,I)
      A6DIFU=WA6(J,I)
      A7DIFU=WA7(J,I)
      A8DIFU=WA8(J,I)
      A9DIFU=WA9(J,I)
      AADIFU=WAA(J,I)
      ABDIFU=WAB(J,I)
      ACDIFU=WAC(J,I)
      ADDIFU=WAD(J,I)
      AEDIFU=WAE(J,I)
      AFDIFU=WAF(J,I)
      AGDIFU=WAG(J,I)
      AHDIFU=WAH(J,I)
      AIDIFU=WAI(J,I)
      AJDIFU=WAJ(J,I)
      B0DIFU=WB0(J,I)
      B1DIFU=WB1(J,I)
      B2DIFU=WB2(J,I)
      B3DIFU=WB3(J,I)
      B4DIFU=WB4(J,I)
      B5DIFU=WB5(J,I)
      B6DIFU=WB6(J,I)
      B7DIFU=WB7(J,I)
      B8DIFU=WB8(J,I)
      B9DIFU=WB9(J,I)
      BADIFU=WBA(J,I)
      BBDIFU=WBB(J,I)
      BCDIFU=WBC(J,I)
      BDDIFU=WBD(J,I)
      BEDIFU=WBE(J,I)
      BFDIFU=WBF(J,I)
      BGDIFU=WBG(J,I)
      BHDIFU=WBH(J,I)
      BIDIFU=WBI(J,I)
      BJDIFU=WBJ(J,I)
      C0DIFU=WC0(J,I)
      C1DIFU=WC1(J,I)
      C2DIFU=WC2(J,I)
      C3DIFU=WC3(J,I)
      C4DIFU=WC4(J,I)
      C5DIFU=WC5(J,I)
      C6DIFU=WC6(J,I)
      C7DIFU=WC7(J,I)
      C8DIFU=WC8(J,I)
      C9DIFU=WC9(J,I)
      CADIFU=WCA(J,I)
C-----------------------------------------------------------------------
      IF(ZDIFU.GE.ZCONV) ZCONV=ZDIFU
      IF(STDIFU.GE.ZCONV) STCONV=STDIFU
      IF(A0DIFU.GE.A0CONV) A0CONV=A0DIFU
      IF(A1DIFU.GE.A1CONV) A1CONV=A1DIFU
      IF(A2DIFU.GE.A2CONV) A2CONV=A2DIFU
      IF(A3DIFU.GE.A3CONV) A3CONV=A3DIFU
      IF(A4DIFU.GE.A4CONV) A4CONV=A4DIFU
      IF(A5DIFU.GE.A5CONV) A5CONV=A5DIFU
      IF(A6DIFU.GE.A6CONV) A6CONV=A6DIFU
      IF(A7DIFU.GE.A7CONV) A7CONV=A7DIFU
      IF(A8DIFU.GE.A8CONV) A8CONV=A8DIFU
      IF(A9DIFU.GE.A9CONV) A9CONV=A9DIFU
      IF(AADIFU.GE.AACONV) AACONV=AADIFU
      IF(ABDIFU.GE.ABCONV) ABCONV=ABDIFU
      IF(ACDIFU.GE.ACCONV) ACCONV=ACDIFU
      IF(ADDIFU.GE.ADCONV) ADCONV=ADDIFU
      IF(AEDIFU.GE.AECONV) AECONV=AEDIFU
      IF(AFDIFU.GE.AFCONV) AFCONV=AFDIFU
      IF(AGDIFU.GE.AGCONV) AGCONV=AGDIFU
      IF(AHDIFU.GE.AHCONV) AHCONV=AHDIFU
      IF(AIDIFU.GE.AICONV) AICONV=AIDIFU
      IF(AJDIFU.GE.AJCONV) AJCONV=AJDIFU
      IF(B0DIFU.GE.B0CONV) B0CONV=B0DIFU
      IF(B1DIFU.GE.B1CONV) B1CONV=B1DIFU
      IF(B2DIFU.GE.B2CONV) B2CONV=B2DIFU
      IF(B3DIFU.GE.B3CONV) B3CONV=B3DIFU
      IF(B4DIFU.GE.B4CONV) B4CONV=B4DIFU
      IF(B5DIFU.GE.B5CONV) B5CONV=B5DIFU
      IF(B6DIFU.GE.B6CONV) B6CONV=B6DIFU
      IF(B7DIFU.GE.B7CONV) B7CONV=B7DIFU
      IF(B8DIFU.GE.B8CONV) B8CONV=B8DIFU
      IF(B9DIFU.GE.B9CONV) B9CONV=B9DIFU
      IF(BADIFU.GE.BACONV) BACONV=BADIFU
      IF(BBDIFU.GE.BBCONV) BBCONV=BBDIFU
      IF(BCDIFU.GE.BCCONV) BCCONV=BCDIFU
      IF(BDDIFU.GE.BDCONV) BDCONV=BDDIFU
      IF(BEDIFU.GE.BECONV) BECONV=BEDIFU
      IF(BFDIFU.GE.BFCONV) BFCONV=BFDIFU
      IF(BGDIFU.GE.BGCONV) BGCONV=BGDIFU
      IF(BHDIFU.GE.BHCONV) BHCONV=BHDIFU
      IF(BIDIFU.GE.BICONV) BICONV=BIDIFU
      IF(BJDIFU.GE.BJCONV) BJCONV=BJDIFU
      IF(C0DIFU.GE.C0CONV) C0CONV=C0DIFU
      IF(C1DIFU.GE.C1CONV) C1CONV=C1DIFU
      IF(C2DIFU.GE.C2CONV) C2CONV=C2DIFU
      IF(C3DIFU.GE.C3CONV) C3CONV=C3DIFU
      IF(C4DIFU.GE.C4CONV) C4CONV=C4DIFU
      IF(C5DIFU.GE.C5CONV) C5CONV=C5DIFU
      IF(C6DIFU.GE.C6CONV) C6CONV=C6DIFU
      IF(C7DIFU.GE.C7CONV) C7CONV=C7DIFU
      IF(C8DIFU.GE.C8CONV) C8CONV=C8DIFU
      IF(C9DIFU.GE.C9CONV) C9CONV=C9DIFU
      IF(CADIFU.GE.CACONV) CACONV=CADIFU
C-----------------------------------------------------------------------
      ZW(J,I)=DTBRX*0.5*(-RHOUW-ZCONV)
      STW(J,I)=DTBRX*0.5*(-RHOUW-STCONV)
      WA0(J,I)=DTBRX*0.5*(-RHOUW-A0CONV)
      WA1(J,I)=DTBRX*0.5*(-RHOUW-A1CONV)
      WA2(J,I)=DTBRX*0.5*(-RHOUW-A2CONV)
      WA3(J,I)=DTBRX*0.5*(-RHOUW-A3CONV)
      WA4(J,I)=DTBRX*0.5*(-RHOUW-A4CONV)
      WA5(J,I)=DTBRX*0.5*(-RHOUW-A5CONV)
      WA6(J,I)=DTBRX*0.5*(-RHOUW-A6CONV)
      WA7(J,I)=DTBRX*0.5*(-RHOUW-A7CONV)
      WA8(J,I)=DTBRX*0.5*(-RHOUW-A8CONV)
      WA9(J,I)=DTBRX*0.5*(-RHOUW-A9CONV)
      WAA(J,I)=DTBRX*0.5*(-RHOUW-AACONV)
      WAB(J,I)=DTBRX*0.5*(-RHOUW-ABCONV)
      WAC(J,I)=DTBRX*0.5*(-RHOUW-ACCONV)
      WAD(J,I)=DTBRX*0.5*(-RHOUW-ADCONV)
      WAE(J,I)=DTBRX*0.5*(-RHOUW-AECONV)
      WAF(J,I)=DTBRX*0.5*(-RHOUW-AFCONV)
      WAG(J,I)=DTBRX*0.5*(-RHOUW-AGCONV)
      WAH(J,I)=DTBRX*0.5*(-RHOUW-AHCONV)
      WAI(J,I)=DTBRX*0.5*(-RHOUW-AICONV)
      WAJ(J,I)=DTBRX*0.5*(-RHOUW-AJCONV)
      WB0(J,I)=DTBRX*0.5*(-RHOUW-B0CONV)
      WB1(J,I)=DTBRX*0.5*(-RHOUW-B1CONV)
      WB2(J,I)=DTBRX*0.5*(-RHOUW-B2CONV)
      WB3(J,I)=DTBRX*0.5*(-RHOUW-B3CONV)
      WB4(J,I)=DTBRX*0.5*(-RHOUW-B4CONV)
      WB5(J,I)=DTBRX*0.5*(-RHOUW-B5CONV)
      WB6(J,I)=DTBRX*0.5*(-RHOUW-B6CONV)
      WB7(J,I)=DTBRX*0.5*(-RHOUW-B7CONV)
      WB8(J,I)=DTBRX*0.5*(-RHOUW-B8CONV)
      WB9(J,I)=DTBRX*0.5*(-RHOUW-B9CONV)
      WBA(J,I)=DTBRX*0.5*(-RHOUW-BACONV)
      WBB(J,I)=DTBRX*0.5*(-RHOUW-BBCONV)
      WBC(J,I)=DTBRX*0.5*(-RHOUW-BCCONV)
      WBD(J,I)=DTBRX*0.5*(-RHOUW-BDCONV)
      WBE(J,I)=DTBRX*0.5*(-RHOUW-BECONV)
      WBF(J,I)=DTBRX*0.5*(-RHOUW-BFCONV)
      WBG(J,I)=DTBRX*0.5*(-RHOUW-BGCONV)
      WBH(J,I)=DTBRX*0.5*(-RHOUW-BHCONV)
      WBI(J,I)=DTBRX*0.5*(-RHOUW-BICONV)
      WBJ(J,I)=DTBRX*0.5*(-RHOUW-BJCONV)
      WC0(J,I)=DTBRX*0.5*(-RHOUW-C0CONV)
      WC1(J,I)=DTBRX*0.5*(-RHOUW-C1CONV)
      WC2(J,I)=DTBRX*0.5*(-RHOUW-C2CONV)
      WC3(J,I)=DTBRX*0.5*(-RHOUW-C3CONV)
      WC4(J,I)=DTBRX*0.5*(-RHOUW-C4CONV)
      WC5(J,I)=DTBRX*0.5*(-RHOUW-C5CONV)
      WC6(J,I)=DTBRX*0.5*(-RHOUW-C6CONV)
      WC7(J,I)=DTBRX*0.5*(-RHOUW-C7CONV)
      WC8(J,I)=DTBRX*0.5*(-RHOUW-C8CONV)
      WC9(J,I)=DTBRX*0.5*(-RHOUW-C9CONV)
      WCA(J,I)=DTBRX*0.5*(-RHOUW-CACONV)
C-----------------------------------------------------------------------
      ZCONV=DABS(RHOVN)
      STCONV=ZCONV
      A0CONV=ZCONV
      A1CONV=ZCONV
      A2CONV=ZCONV
      A3CONV=ZCONV
      A4CONV=ZCONV
      A5CONV=ZCONV
      A6CONV=ZCONV
      A7CONV=ZCONV
      A8CONV=ZCONV
      A9CONV=ZCONV
      AACONV=ZCONV
      ABCONV=ZCONV
      ACCONV=ZCONV
      ADCONV=ZCONV
      AECONV=ZCONV
      AFCONV=ZCONV
      AGCONV=ZCONV
      AHCONV=ZCONV
      AICONV=ZCONV
      AJCONV=ZCONV
      B0CONV=ZCONV
      B1CONV=ZCONV
      B2CONV=ZCONV
      B3CONV=ZCONV
      B4CONV=ZCONV
      B5CONV=ZCONV
      B6CONV=ZCONV
      B7CONV=ZCONV
      B8CONV=ZCONV
      B9CONV=ZCONV
      BACONV=ZCONV
      BBCONV=ZCONV
      BCCONV=ZCONV
      BDCONV=ZCONV
      BECONV=ZCONV
      BFCONV=ZCONV
      BGCONV=ZCONV
      BHCONV=ZCONV
      BICONV=ZCONV
      BJCONV=ZCONV
      C0CONV=ZCONV
      C1CONV=ZCONV
      C2CONV=ZCONV
      C3CONV=ZCONV
      C4CONV=ZCONV
      C5CONV=ZCONV
      C6CONV=ZCONV
      C7CONV=ZCONV
      C8CONV=ZCONV
      C9CONV=ZCONV
      CACONV=ZCONV
C-----------------------------------------------------------------------
      ZDIFU=ZS(J+1,I)
      STDIFU=STS(J+1,I)
      A0DIFU=QA0(J+1,I)
      A1DIFU=QA1(J+1,I)
      A2DIFU=QA2(J+1,I)
      A3DIFU=QA3(J+1,I)
      A4DIFU=QA4(J+1,I)
      A5DIFU=QA5(J+1,I)
      A6DIFU=QA6(J+1,I)
      A7DIFU=QA7(J+1,I)
      A8DIFU=QA8(J+1,I)
      A9DIFU=QA9(J+1,I)
      AADIFU=QAA(J+1,I)
      ABDIFU=QAB(J+1,I)
      ACDIFU=QAC(J+1,I)
      ADDIFU=QAD(J+1,I)
      AEDIFU=QAE(J+1,I)
      AFDIFU=QAF(J+1,I)
      AGDIFU=QAG(J+1,I)
      AHDIFU=QAH(J+1,I)
      AIDIFU=QAI(J+1,I)
      AJDIFU=QAJ(J+1,I)
      B0DIFU=QB0(J+1,I)
      B1DIFU=QB1(J+1,I)
      B2DIFU=QB2(J+1,I)
      B3DIFU=QB3(J+1,I)
      B4DIFU=QB4(J+1,I)
      B5DIFU=QB5(J+1,I)
      B6DIFU=QB6(J+1,I)
      B7DIFU=QB7(J+1,I)
      B8DIFU=QB8(J+1,I)
      B9DIFU=QB9(J+1,I)
      BADIFU=QBA(J+1,I)
      BBDIFU=QBB(J+1,I)
      BCDIFU=QBC(J+1,I)
      BDDIFU=QBD(J+1,I)
      BEDIFU=QBE(J+1,I)
      BFDIFU=QBF(J+1,I)
      BGDIFU=QBG(J+1,I)
      BHDIFU=QBH(J+1,I)
      BIDIFU=QBI(J+1,I)
      BJDIFU=QBJ(J+1,I)
      C0DIFU=QC0(J+1,I)
      C1DIFU=QC1(J+1,I)
      C2DIFU=QC2(J+1,I)
      C3DIFU=QC3(J+1,I)
      C4DIFU=QC4(J+1,I)
      C5DIFU=QC5(J+1,I)
      C6DIFU=QC6(J+1,I)
      C7DIFU=QC7(J+1,I)
      C8DIFU=QC8(J+1,I)
      C9DIFU=QC9(J+1,I)
      CADIFU=QCA(J+1,I)
C-----------------------------------------------------------------------
      IF(ZDIFU.GE.ZCONV) ZCONV=ZDIFU
      IF(STDIFU.GE.STCONV) STCONV=STDIFU
      IF(A0DIFU.GE.A0CONV) A0CONV=A0DIFU
      IF(A1DIFU.GE.A1CONV) A1CONV=A1DIFU
      IF(A2DIFU.GE.A2CONV) A2CONV=A2DIFU
      IF(A3DIFU.GE.A3CONV) A3CONV=A3DIFU
      IF(A4DIFU.GE.A4CONV) A4CONV=A4DIFU
      IF(A5DIFU.GE.A5CONV) A5CONV=A5DIFU
      IF(A6DIFU.GE.A6CONV) A6CONV=A6DIFU
      IF(A7DIFU.GE.A7CONV) A7CONV=A7DIFU
      IF(A8DIFU.GE.A8CONV) A8CONV=A8DIFU
      IF(A9DIFU.GE.A9CONV) A9CONV=A9DIFU
      IF(AADIFU.GE.AACONV) AACONV=AADIFU
      IF(ABDIFU.GE.ABCONV) ABCONV=ABDIFU
      IF(ACDIFU.GE.ACCONV) ACCONV=ACDIFU
      IF(ADDIFU.GE.ADCONV) ADCONV=ADDIFU
      IF(AEDIFU.GE.AECONV) AECONV=AEDIFU
      IF(AFDIFU.GE.AFCONV) AFCONV=AFDIFU
      IF(AGDIFU.GE.AGCONV) AGCONV=AGDIFU
      IF(AHDIFU.GE.AHCONV) AHCONV=AHDIFU
      IF(AIDIFU.GE.AICONV) AICONV=AIDIFU
      IF(AJDIFU.GE.AJCONV) AJCONV=AJDIFU
      IF(B0DIFU.GE.B0CONV) B0CONV=B0DIFU
      IF(B1DIFU.GE.B1CONV) B1CONV=B1DIFU
      IF(B2DIFU.GE.B2CONV) B2CONV=B2DIFU
      IF(B3DIFU.GE.B3CONV) B3CONV=B3DIFU
      IF(B4DIFU.GE.B4CONV) B4CONV=B4DIFU
      IF(B5DIFU.GE.B5CONV) B5CONV=B5DIFU
      IF(B6DIFU.GE.B6CONV) B6CONV=B6DIFU
      IF(B7DIFU.GE.B7CONV) B7CONV=B7DIFU
      IF(B8DIFU.GE.B8CONV) B8CONV=B8DIFU
      IF(B9DIFU.GE.B9CONV) B9CONV=B9DIFU
      IF(BADIFU.GE.BACONV) BACONV=BADIFU
      IF(BBDIFU.GE.BBCONV) BBCONV=BBDIFU
      IF(BCDIFU.GE.BCCONV) BCCONV=BCDIFU
      IF(BDDIFU.GE.BDCONV) BDCONV=BDDIFU
      IF(BEDIFU.GE.BECONV) BECONV=BEDIFU
      IF(BFDIFU.GE.BFCONV) BFCONV=BFDIFU
      IF(BGDIFU.GE.BGCONV) BGCONV=BGDIFU
      IF(BHDIFU.GE.BHCONV) BHCONV=BHDIFU
      IF(BIDIFU.GE.BICONV) BICONV=BIDIFU
      IF(BJDIFU.GE.BJCONV) BJCONV=BJDIFU
      IF(C0DIFU.GE.C0CONV) C0CONV=C0DIFU
      IF(C1DIFU.GE.C1CONV) C1CONV=C1DIFU
      IF(C2DIFU.GE.C2CONV) C2CONV=C2DIFU
      IF(C3DIFU.GE.C3CONV) C3CONV=C3DIFU
      IF(C4DIFU.GE.C4CONV) C4CONV=C4DIFU
      IF(C5DIFU.GE.C5CONV) C5CONV=C5DIFU
      IF(C6DIFU.GE.C6CONV) C6CONV=C6DIFU
      IF(C7DIFU.GE.C7CONV) C7CONV=C7DIFU
      IF(C8DIFU.GE.C8CONV) C8CONV=C8DIFU
      IF(C9DIFU.GE.C9CONV) C9CONV=C9DIFU
      IF(CADIFU.GE.CACONV) CACONV=CADIFU
C-----------------------------------------------------------------------
      ZN(J,I)=DTBRY*0.5*(RHOVN-ZCONV)-SYMZ/DYN
      STN(J,I)=DTBRY*0.5*(RHOVN-STCONV)-SYMST/DYN
      PA0(J,I)=DTBRY*0.5*(RHOVN-A0CONV)-SYMA0/DYN
      PA1(J,I)=DTBRY*0.5*(RHOVN-A1CONV)-SYMA1/DYN
      PA2(J,I)=DTBRY*0.5*(RHOVN-A2CONV)-SYMA2/DYN
      PA3(J,I)=DTBRY*0.5*(RHOVN-A3CONV)-SYMA3/DYN
      PA4(J,I)=DTBRY*0.5*(RHOVN-A4CONV)-SYMA4/DYN
      PA5(J,I)=DTBRY*0.5*(RHOVN-A5CONV)-SYMA5/DYN
      PA6(J,I)=DTBRY*0.5*(RHOVN-A6CONV)-SYMA6/DYN
      PA7(J,I)=DTBRY*0.5*(RHOVN-A7CONV)-SYMA7/DYN
      PA8(J,I)=DTBRY*0.5*(RHOVN-A8CONV)-SYMA8/DYN
      PA9(J,I)=DTBRY*0.5*(RHOVN-A9CONV)-SYMA9/DYN
      PAA(J,I)=DTBRY*0.5*(RHOVN-AACONV)-SYMAA/DYN
      PAB(J,I)=DTBRY*0.5*(RHOVN-ABCONV)-SYMAB/DYN
      PAC(J,I)=DTBRY*0.5*(RHOVN-ACCONV)-SYMAC/DYN
      PAD(J,I)=DTBRY*0.5*(RHOVN-ADCONV)-SYMAD/DYN
      PAE(J,I)=DTBRY*0.5*(RHOVN-AECONV)-SYMAE/DYN
      PAF(J,I)=DTBRY*0.5*(RHOVN-AFCONV)-SYMAF/DYN
      PAG(J,I)=DTBRY*0.5*(RHOVN-AGCONV)-SYMAG/DYN
      PAH(J,I)=DTBRY*0.5*(RHOVN-AHCONV)-SYMAH/DYN
      PAI(J,I)=DTBRY*0.5*(RHOVN-AICONV)-SYMAI/DYN
      PAJ(J,I)=DTBRY*0.5*(RHOVN-AJCONV)-SYMAJ/DYN
      PB0(J,I)=DTBRY*0.5*(RHOVN-B0CONV)-SYMB0/DYN
      PB1(J,I)=DTBRY*0.5*(RHOVN-B1CONV)-SYMB1/DYN
      PB2(J,I)=DTBRY*0.5*(RHOVN-B2CONV)-SYMB2/DYN
      PB3(J,I)=DTBRY*0.5*(RHOVN-B3CONV)-SYMB3/DYN
      PB4(J,I)=DTBRY*0.5*(RHOVN-B4CONV)-SYMB4/DYN
      PB5(J,I)=DTBRY*0.5*(RHOVN-B5CONV)-SYMB5/DYN
      PB6(J,I)=DTBRY*0.5*(RHOVN-B6CONV)-SYMB6/DYN
      PB7(J,I)=DTBRY*0.5*(RHOVN-B7CONV)-SYMB7/DYN
      PB8(J,I)=DTBRY*0.5*(RHOVN-B8CONV)-SYMB8/DYN
      PB9(J,I)=DTBRY*0.5*(RHOVN-B9CONV)-SYMB9/DYN
      PBA(J,I)=DTBRY*0.5*(RHOVN-BACONV)-SYMBA/DYN
      PBB(J,I)=DTBRY*0.5*(RHOVN-BBCONV)-SYMBB/DYN
      PBC(J,I)=DTBRY*0.5*(RHOVN-BCCONV)-SYMBC/DYN
      PBD(J,I)=DTBRY*0.5*(RHOVN-BDCONV)-SYMBD/DYN
      PBE(J,I)=DTBRY*0.5*(RHOVN-BECONV)-SYMBE/DYN
      PBF(J,I)=DTBRY*0.5*(RHOVN-BFCONV)-SYMBF/DYN
      PBG(J,I)=DTBRY*0.5*(RHOVN-BGCONV)-SYMBG/DYN
      PBH(J,I)=DTBRY*0.5*(RHOVN-BHCONV)-SYMBH/DYN
      PBI(J,I)=DTBRY*0.5*(RHOVN-BICONV)-SYMBI/DYN
      PBJ(J,I)=DTBRY*0.5*(RHOVN-BJCONV)-SYMBJ/DYN
      PC0(J,I)=DTBRY*0.5*(RHOVN-C0CONV)-SYMC0/DYN
      PC1(J,I)=DTBRY*0.5*(RHOVN-C1CONV)-SYMC1/DYN
      PC2(J,I)=DTBRY*0.5*(RHOVN-C2CONV)-SYMC2/DYN
      PC3(J,I)=DTBRY*0.5*(RHOVN-C3CONV)-SYMC3/DYN
      PC4(J,I)=DTBRY*0.5*(RHOVN-C4CONV)-SYMC4/DYN
      PC5(J,I)=DTBRY*0.5*(RHOVN-C5CONV)-SYMC5/DYN
      PC6(J,I)=DTBRY*0.5*(RHOVN-C6CONV)-SYMC6/DYN
      PC7(J,I)=DTBRY*0.5*(RHOVN-C7CONV)-SYMC7/DYN
      PC8(J,I)=DTBRY*0.5*(RHOVN-C8CONV)-SYMC8/DYN
      PC9(J,I)=DTBRY*0.5*(RHOVN-C9CONV)-SYMC9/DYN
      PCA(J,I)=DTBRY*0.5*(RHOVN-CACONV)-SYMCA/DYN
C-----------------------------------------------------------------------
      ZCONV=DABS(RHOVS)
      STCONV=ZCONV
      A0CONV=ZCONV
      A1CONV=ZCONV
      A2CONV=ZCONV
      A3CONV=ZCONV
      A4CONV=ZCONV
      A5CONV=ZCONV
      A6CONV=ZCONV
      A7CONV=ZCONV
      A8CONV=ZCONV
      A9CONV=ZCONV
      AACONV=ZCONV
      ABCONV=ZCONV
      ACCONV=ZCONV
      ADCONV=ZCONV
      AECONV=ZCONV
      AFCONV=ZCONV
      AGCONV=ZCONV
      AHCONV=ZCONV
      AICONV=ZCONV
      AJCONV=ZCONV
      B0CONV=ZCONV
      B1CONV=ZCONV
      B2CONV=ZCONV
      B3CONV=ZCONV
      B4CONV=ZCONV
      B5CONV=ZCONV
      B6CONV=ZCONV
      B7CONV=ZCONV
      B8CONV=ZCONV
      B9CONV=ZCONV
      BACONV=ZCONV
      BBCONV=ZCONV
      BCCONV=ZCONV
      BDCONV=ZCONV
      BECONV=ZCONV
      BFCONV=ZCONV
      BGCONV=ZCONV
      BHCONV=ZCONV
      BICONV=ZCONV
      BJCONV=ZCONV
      C0CONV=ZCONV
      C1CONV=ZCONV
      C2CONV=ZCONV
      C3CONV=ZCONV
      C4CONV=ZCONV
      C5CONV=ZCONV
      C6CONV=ZCONV
      C7CONV=ZCONV
      C8CONV=ZCONV
      C9CONV=ZCONV
      CACONV=ZCONV
C-----------------------------------------------------------------------
      ZDIFU=ZS(J,I)
      STDIFU=STS(J,I)
      A0DIFU=QA0(J,I)
      A1DIFU=QA1(J,I)
      A2DIFU=QA2(J,I)
      A3DIFU=QA3(J,I)
      A4DIFU=QA4(J,I)
      A5DIFU=QA5(J,I)
      A6DIFU=QA6(J,I)
      A7DIFU=QA7(J,I)
      A8DIFU=QA8(J,I)
      A9DIFU=QA9(J,I)
      AADIFU=QAA(J,I)
      ABDIFU=QAB(J,I)
      ACDIFU=QAC(J,I)
      ADDIFU=QAD(J,I)
      AEDIFU=QAE(J,I)
      AFDIFU=QAF(J,I)
      AGDIFU=QAG(J,I)
      AHDIFU=QAH(J,I)
      AIDIFU=QAI(J,I)
      AJDIFU=QAJ(J,I)
      B0DIFU=QB0(J,I)
      B1DIFU=QB1(J,I)
      B2DIFU=QB2(J,I)
      B3DIFU=QB3(J,I)
      B4DIFU=QB4(J,I)
      B5DIFU=QB5(J,I)
      B6DIFU=QB6(J,I)
      B7DIFU=QB7(J,I)
      B8DIFU=QB8(J,I)
      B9DIFU=QB9(J,I)
      BADIFU=QBA(J,I)
      BBDIFU=QBB(J,I)
      BCDIFU=QBC(J,I)
      BDDIFU=QBD(J,I)
      BEDIFU=QBE(J,I)
      BFDIFU=QBF(J,I)
      BGDIFU=QBG(J,I)
      BHDIFU=QBH(J,I)
      BIDIFU=QBI(J,I)
      BJDIFU=QBJ(J,I)
      C0DIFU=QC0(J,I)
      C1DIFU=QC1(J,I)
      C2DIFU=QC2(J,I)
      C3DIFU=QC3(J,I)
      C4DIFU=QC4(J,I)
      C5DIFU=QC5(J,I)
      C6DIFU=QC6(J,I)
      C7DIFU=QC7(J,I)
      C8DIFU=QC8(J,I)
      C9DIFU=QC9(J,I)
      CADIFU=QCA(J,I)
C-----------------------------------------------------------------------
      IF(ZDIFU.GE.ZCONV) ZCONV=ZDIFU
      IF(STDIFU.GE.STCONV) STCONV=STDIFU
      IF(A0DIFU.GE.A0CONV) A0CONV=A0DIFU
      IF(A1DIFU.GE.A1CONV) A1CONV=A1DIFU
      IF(A2DIFU.GE.A2CONV) A2CONV=A2DIFU
      IF(A3DIFU.GE.A3CONV) A3CONV=A3DIFU
      IF(A4DIFU.GE.A4CONV) A4CONV=A4DIFU
      IF(A5DIFU.GE.A5CONV) A5CONV=A5DIFU
      IF(A6DIFU.GE.A6CONV) A6CONV=A6DIFU
      IF(A7DIFU.GE.A7CONV) A7CONV=A7DIFU
      IF(A8DIFU.GE.A8CONV) A8CONV=A8DIFU
      IF(A9DIFU.GE.A9CONV) A9CONV=A9DIFU
      IF(AADIFU.GE.AACONV) AACONV=AADIFU
      IF(ABDIFU.GE.ABCONV) ABCONV=ABDIFU
      IF(ACDIFU.GE.ACCONV) ACCONV=ACDIFU
      IF(ADDIFU.GE.ADCONV) ADCONV=ADDIFU
      IF(AEDIFU.GE.AECONV) AECONV=AEDIFU
      IF(AFDIFU.GE.AFCONV) AFCONV=AFDIFU
      IF(AGDIFU.GE.AGCONV) AGCONV=AGDIFU
      IF(AHDIFU.GE.AHCONV) AHCONV=AHDIFU
      IF(AIDIFU.GE.AICONV) AICONV=AIDIFU
      IF(AJDIFU.GE.AJCONV) AJCONV=AJDIFU
      IF(B0DIFU.GE.B0CONV) B0CONV=B0DIFU
      IF(B1DIFU.GE.B1CONV) B1CONV=B1DIFU
      IF(B2DIFU.GE.B2CONV) B2CONV=B2DIFU
      IF(B3DIFU.GE.B3CONV) B3CONV=B3DIFU
      IF(B4DIFU.GE.B4CONV) B4CONV=B4DIFU
      IF(B5DIFU.GE.B5CONV) B5CONV=B5DIFU
      IF(B6DIFU.GE.B6CONV) B6CONV=B6DIFU
      IF(B7DIFU.GE.B7CONV) B7CONV=B7DIFU
      IF(B8DIFU.GE.B8CONV) B8CONV=B8DIFU
      IF(B9DIFU.GE.B9CONV) B9CONV=B9DIFU
      IF(BADIFU.GE.BACONV) BACONV=BADIFU
      IF(BBDIFU.GE.BBCONV) BBCONV=BBDIFU
      IF(BCDIFU.GE.BCCONV) BCCONV=BCDIFU
      IF(BDDIFU.GE.BDCONV) BDCONV=BDDIFU
      IF(BEDIFU.GE.BECONV) BECONV=BEDIFU
      IF(BFDIFU.GE.BFCONV) BFCONV=BFDIFU
      IF(BGDIFU.GE.BGCONV) BGCONV=BGDIFU
      IF(BHDIFU.GE.BHCONV) BHCONV=BHDIFU
      IF(BIDIFU.GE.BICONV) BICONV=BIDIFU
      IF(BJDIFU.GE.BJCONV) BJCONV=BJDIFU
      IF(C0DIFU.GE.C0CONV) C0CONV=C0DIFU
      IF(C1DIFU.GE.C1CONV) C1CONV=C1DIFU
      IF(C2DIFU.GE.C2CONV) C2CONV=C2DIFU
      IF(C3DIFU.GE.C3CONV) C3CONV=C3DIFU
      IF(C4DIFU.GE.C4CONV) C4CONV=C4DIFU
      IF(C5DIFU.GE.C5CONV) C5CONV=C5DIFU
      IF(C6DIFU.GE.C6CONV) C6CONV=C6DIFU
      IF(C7DIFU.GE.C7CONV) C7CONV=C7DIFU
      IF(C8DIFU.GE.C8CONV) C8CONV=C8DIFU
      IF(C9DIFU.GE.C9CONV) C9CONV=C9DIFU
      IF(CADIFU.GE.CACONV) CACONV=CADIFU
C-----------------------------------------------------------------------
      ZS(J,I)=DTBRY*0.5*(-RHOVS-ZCONV)+SYMZ/DYS
      STS(J,I)=DTBRY*0.5*(-RHOVS-STCONV)+SYMST/DYS
      QA0(J,I)=DTBRY*0.5*(-RHOVS-A0CONV)+SYMA0/DYS
      QA1(J,I)=DTBRY*0.5*(-RHOVS-A1CONV)+SYMA1/DYS
      QA2(J,I)=DTBRY*0.5*(-RHOVS-A2CONV)+SYMA2/DYS
      QA3(J,I)=DTBRY*0.5*(-RHOVS-A3CONV)+SYMA3/DYS
      QA4(J,I)=DTBRY*0.5*(-RHOVS-A4CONV)+SYMA4/DYS
      QA5(J,I)=DTBRY*0.5*(-RHOVS-A5CONV)+SYMA5/DYS
      QA6(J,I)=DTBRY*0.5*(-RHOVS-A6CONV)+SYMA6/DYS
      QA7(J,I)=DTBRY*0.5*(-RHOVS-A7CONV)+SYMA7/DYS
      QA8(J,I)=DTBRY*0.5*(-RHOVS-A8CONV)+SYMA8/DYS
      QA9(J,I)=DTBRY*0.5*(-RHOVS-A9CONV)+SYMA9/DYS
      QAA(J,I)=DTBRY*0.5*(-RHOVS-AACONV)+SYMAA/DYS
      QAB(J,I)=DTBRY*0.5*(-RHOVS-ABCONV)+SYMAB/DYS
      QAC(J,I)=DTBRY*0.5*(-RHOVS-ACCONV)+SYMAC/DYS
      QAD(J,I)=DTBRY*0.5*(-RHOVS-ADCONV)+SYMAD/DYS
      QAE(J,I)=DTBRY*0.5*(-RHOVS-AECONV)+SYMAE/DYS
      QAF(J,I)=DTBRY*0.5*(-RHOVS-AFCONV)+SYMAF/DYS
      QAG(J,I)=DTBRY*0.5*(-RHOVS-AGCONV)+SYMAG/DYS
      QAH(J,I)=DTBRY*0.5*(-RHOVS-AHCONV)+SYMAH/DYS
      QAI(J,I)=DTBRY*0.5*(-RHOVS-AICONV)+SYMAI/DYS
      QAJ(J,I)=DTBRY*0.5*(-RHOVS-AJCONV)+SYMAJ/DYS
      QB0(J,I)=DTBRY*0.5*(-RHOVS-B0CONV)+SYMB0/DYS
      QB1(J,I)=DTBRY*0.5*(-RHOVS-B1CONV)+SYMB1/DYS
      QB2(J,I)=DTBRY*0.5*(-RHOVS-B2CONV)+SYMB2/DYS
      QB3(J,I)=DTBRY*0.5*(-RHOVS-B3CONV)+SYMB3/DYS
      QB4(J,I)=DTBRY*0.5*(-RHOVS-B4CONV)+SYMB4/DYS
      QB5(J,I)=DTBRY*0.5*(-RHOVS-B5CONV)+SYMB5/DYS
      QB6(J,I)=DTBRY*0.5*(-RHOVS-B6CONV)+SYMB6/DYS
      QB7(J,I)=DTBRY*0.5*(-RHOVS-B7CONV)+SYMB7/DYS
      QB8(J,I)=DTBRY*0.5*(-RHOVS-B8CONV)+SYMB8/DYS
      QB9(J,I)=DTBRY*0.5*(-RHOVS-B9CONV)+SYMB9/DYS
      QBA(J,I)=DTBRY*0.5*(-RHOVS-BACONV)+SYMBA/DYS
      QBB(J,I)=DTBRY*0.5*(-RHOVS-BBCONV)+SYMBB/DYS
      QBC(J,I)=DTBRY*0.5*(-RHOVS-BCCONV)+SYMBC/DYS
      QBD(J,I)=DTBRY*0.5*(-RHOVS-BDCONV)+SYMBD/DYS
      QBE(J,I)=DTBRY*0.5*(-RHOVS-BECONV)+SYMBE/DYS
      QBF(J,I)=DTBRY*0.5*(-RHOVS-BFCONV)+SYMBF/DYS
      QBG(J,I)=DTBRY*0.5*(-RHOVS-BGCONV)+SYMBG/DYS
      QBH(J,I)=DTBRY*0.5*(-RHOVS-BHCONV)+SYMBH/DYS
      QBI(J,I)=DTBRY*0.5*(-RHOVS-BICONV)+SYMBI/DYS
      QBJ(J,I)=DTBRY*0.5*(-RHOVS-BJCONV)+SYMBJ/DYS
      QC0(J,I)=DTBRY*0.5*(-RHOVS-C0CONV)+SYMC0/DYS
      QC1(J,I)=DTBRY*0.5*(-RHOVS-C1CONV)+SYMC1/DYS
      QC2(J,I)=DTBRY*0.5*(-RHOVS-C2CONV)+SYMC2/DYS
      QC3(J,I)=DTBRY*0.5*(-RHOVS-C3CONV)+SYMC3/DYS
      QC4(J,I)=DTBRY*0.5*(-RHOVS-C4CONV)+SYMC4/DYS
      QC5(J,I)=DTBRY*0.5*(-RHOVS-C5CONV)+SYMC5/DYS
      QC6(J,I)=DTBRY*0.5*(-RHOVS-C6CONV)+SYMC6/DYS
      QC7(J,I)=DTBRY*0.5*(-RHOVS-C7CONV)+SYMC7/DYS
      QC8(J,I)=DTBRY*0.5*(-RHOVS-C8CONV)+SYMC8/DYS
      QC9(J,I)=DTBRY*0.5*(-RHOVS-C9CONV)+SYMC9/DYS
      QCA(J,I)=DTBRY*0.5*(-RHOVS-CACONV)+SYMCA/DYS
C
   21 CONTINUE
      ENDDO
   20 CONTINUE
      IF(ICHEM.LE.0) GO TO 399
C--------------------------FIND REACTION RATES--------------------------
      CALL CKRATES
C-----------------SOLVE THE SPECIES-ALGEBRAIC EQUATIONS-----------------
      CALL SOLVESP(ISOR1,RELXSP,TOLRSP,SPNORM)
  399 CONTINUE
C------------------------SOLVING ENTHALPY EQUATION-----------------------
      IF(ITHRM.GT.0) CALL SOLVEH(ISOR2,RELXH,TOLRH,SIGSP,HNORM)
      RESDH=0.0
      RESDC=0.0
      DO 600 I=2,LI-1
      DO J=2,LJ-1
      IF(ISKIP(J,I).GE.3) GO TO 601
      RESDH=RESDH+DABS(FPZ(J,I)-HT(J,I))
      RESDC=RESDC+DABS(SST1(J,I)-STMF(J,I))
C     RESDC=RESDC+DABS(SST2(J,I)-STND(J,I))
      RESDC=RESDC+DABS(SA0(J,I)-FA0(J,I))
      RESDC=RESDC+DABS(SA1(J,I)-FA1(J,I))
      RESDC=RESDC+DABS(SA2(J,I)-FA2(J,I))
      RESDC=RESDC+DABS(SA3(J,I)-FA3(J,I))
      RESDC=RESDC+DABS(SA4(J,I)-FA4(J,I))
      RESDC=RESDC+DABS(SA5(J,I)-FA5(J,I))
      RESDC=RESDC+DABS(SA6(J,I)-FA6(J,I))
      RESDC=RESDC+DABS(SA7(J,I)-FA7(J,I))
      RESDC=RESDC+DABS(SA8(J,I)-FA8(J,I))
      RESDC=RESDC+DABS(SA9(J,I)-FA9(J,I))
      RESDC=RESDC+DABS(SAA(J,I)-FAA(J,I))
      RESDC=RESDC+DABS(SAB(J,I)-FAB(J,I))
      RESDC=RESDC+DABS(SAC(J,I)-FAC(J,I))
      RESDC=RESDC+DABS(SAD(J,I)-FAD(J,I))
      RESDC=RESDC+DABS(SAE(J,I)-FAE(J,I))
      RESDC=RESDC+DABS(SAF(J,I)-FAF(J,I))
      RESDC=RESDC+DABS(SAG(J,I)-FAG(J,I))
      RESDC=RESDC+DABS(SAH(J,I)-FAH(J,I))
      RESDC=RESDC+DABS(SAI(J,I)-FAI(J,I))
      RESDC=RESDC+DABS(SAJ(J,I)-FAJ(J,I))
      RESDC=RESDC+DABS(SB0(J,I)-FB0(J,I))
      RESDC=RESDC+DABS(SB1(J,I)-FB1(J,I))
      RESDC=RESDC+DABS(SB2(J,I)-FB2(J,I))
      RESDC=RESDC+DABS(SB3(J,I)-FB3(J,I))
      RESDC=RESDC+DABS(SB4(J,I)-FB4(J,I))
      RESDC=RESDC+DABS(SB5(J,I)-FB5(J,I))
      RESDC=RESDC+DABS(SB6(J,I)-FB6(J,I))
      RESDC=RESDC+DABS(SB7(J,I)-FB7(J,I))
      RESDC=RESDC+DABS(SB8(J,I)-FB8(J,I))
      RESDC=RESDC+DABS(SB9(J,I)-FB9(J,I))
      RESDC=RESDC+DABS(SBA(J,I)-FBA(J,I))
      RESDC=RESDC+DABS(SBB(J,I)-FBB(J,I))
      RESDC=RESDC+DABS(SBC(J,I)-FBC(J,I))
      RESDC=RESDC+DABS(SBD(J,I)-FBD(J,I))
      RESDC=RESDC+DABS(SBE(J,I)-FBE(J,I))
      RESDC=RESDC+DABS(SBF(J,I)-FBF(J,I))
      RESDC=RESDC+DABS(SBG(J,I)-FBG(J,I))
      RESDC=RESDC+DABS(SBH(J,I)-FBH(J,I))
      RESDC=RESDC+DABS(SBI(J,I)-FBI(J,I))
      RESDC=RESDC+DABS(SBJ(J,I)-FBJ(J,I))
      RESDC=RESDC+DABS(SC0(J,I)-FC0(J,I))
      RESDC=RESDC+DABS(SC1(J,I)-FC1(J,I))
      RESDC=RESDC+DABS(SC2(J,I)-FC2(J,I))
      RESDC=RESDC+DABS(SC3(J,I)-FC3(J,I))
      RESDC=RESDC+DABS(SC4(J,I)-FC4(J,I))
      RESDC=RESDC+DABS(SC5(J,I)-FC5(J,I))
      RESDC=RESDC+DABS(SC6(J,I)-FC6(J,I))
      RESDC=RESDC+DABS(SC7(J,I)-FC7(J,I))
      RESDC=RESDC+DABS(SC8(J,I)-FC8(J,I))
      RESDC=RESDC+DABS(SC9(J,I)-FC9(J,I))
      RESDC=RESDC+DABS(SCA(J,I)-FCA(J,I))
      HT(J,I)=FPZ(J,I)
      STMF(J,I)=SST1(J,I)
      STND(J,I)=SST2(J,I)
      FA0(J,I)=SA0(J,I)
      FA1(J,I)=SA1(J,I)
      FA2(J,I)=SA2(J,I)
      FA3(J,I)=SA3(J,I)
      FA4(J,I)=SA4(J,I)
      FA5(J,I)=SA5(J,I)
      FA6(J,I)=SA6(J,I)
      FA7(J,I)=SA7(J,I)
      FA8(J,I)=SA8(J,I)
      FA9(J,I)=SA9(J,I)
      FAA(J,I)=SAA(J,I)
      FAB(J,I)=SAB(J,I)
      FAC(J,I)=SAC(J,I)
      FAD(J,I)=SAD(J,I)
      FAE(J,I)=SAE(J,I)
      FAF(J,I)=SAF(J,I)
      FAG(J,I)=SAG(J,I)
      FAH(J,I)=SAH(J,I)
      FAI(J,I)=SAI(J,I)
      FAJ(J,I)=SAJ(J,I)
      FB0(J,I)=SB0(J,I)
      FB1(J,I)=SB1(J,I)
      FB2(J,I)=SB2(J,I)
      FB3(J,I)=SB3(J,I)
      FB4(J,I)=SB4(J,I)
      FB5(J,I)=SB5(J,I)
      FB6(J,I)=SB6(J,I)
      FB7(J,I)=SB7(J,I)
      FB8(J,I)=SB8(J,I)
      FB9(J,I)=SB9(J,I)
      FBA(J,I)=SBA(J,I)
      FBB(J,I)=SBB(J,I)
      FBC(J,I)=SBC(J,I)
      FBD(J,I)=SBD(J,I)
      FBE(J,I)=SBE(J,I)
      FBF(J,I)=SBF(J,I)
      FBG(J,I)=SBG(J,I)
      FBH(J,I)=SBH(J,I)
      FBI(J,I)=SBI(J,I)
      FBJ(J,I)=SBJ(J,I)
      FC0(J,I)=SC0(J,I)
      FC1(J,I)=SC1(J,I)
      FC2(J,I)=SC2(J,I)
      FC3(J,I)=SC3(J,I)
      FC4(J,I)=SC4(J,I)
      FC5(J,I)=SC5(J,I)
      FC6(J,I)=SC6(J,I)
      FC7(J,I)=SC7(J,I)
      FC8(J,I)=SC8(J,I)
      FC9(J,I)=SC9(J,I)
      FCA(J,I)=SCA(J,I)
  601 CONTINUE
      ENDDO
  600 CONTINUE
      RESDH=RESDH/HNORM
      RESDC=RESDC/SPNORM
      RETURN
      END